export const Resources = {
    Icons : {
        Empty24x24Image : 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMTZEaa/1AAAARElEQVRIS7XIIQEAMAwEsfo3/TMQeAMhuW1fMUvMErPELDFLzBKzxCwxS8wSs8QsMUvMErPELDFLzBKzxCwxS8wSs7N7f5G5m9/crGEAAAAASUVORK5CYII='
    }
}