import React from "../../../../preact/compat";
import { Teact } from '../Teact';

export class ColumnComponent extends React.Component {
    static defaultProps = {
        columnKey: null,
        field: null,
        sortField: null,
        filterField: null,
        header: null,
        body: null,
        loadingBody: null,
        footer: null,
        sortable: false,
        sortableDisabled: false,
        sortFunction: null,
        filter: false,
        filterMatchMode: 'startsWith',
        filterPlaceholder: null,
        filterType: 'text',
        filterMaxLength: null,
        filterElement: null,
        filterFunction: null,
        filterHeaderStyle: null,
        filterHeaderClassName: null,
        style: null,
        className: null,
        headerStyle: null,
        headerClassName: null,
        bodyStyle: null,
        bodyClassName: null,
        footerStyle: null,
        footerClassName: null,
        expander: false,
        frozen: false,
        selectionMode: null,
        colSpan: null,
        rowSpan: null,
        editor: null,
        editorValidator: null,
        editorValidatorEvent: 'click',
        onBeforeEditorHide: null,
        onBeforeEditorShow: null,
        onEditorInit: null,
        onEditorSubmit: null,
        onEditorCancel: null,
        excludeGlobalFilter: false,
        rowReorder: false,
        rowReorderIcon: 'pi pi-bars',
        rowEditor: false,
        exportable: true,
        reorderable: true
    }
}
