import { ColorClass } from "./thema-system/ColorClass";



export function Color(value: string): ColorClass {
    return new ColorClass(value)
}


export namespace Color {
    export let black = new ColorClass('white');
    export let navy = new ColorClass('white');
    export let darkblue = new ColorClass('white');
    export let mediumblue = new ColorClass('white');
    export let blue = new ColorClass('white');
    export let darkgreen = new ColorClass('white');
    export let green = new ColorClass('white');
    export let teal = new ColorClass('white');
    export let darkcyan = new ColorClass('white');
    export let deepskyblue = new ColorClass('white');
    export let darkturquoise = new ColorClass('white');
    export let mediumspringgreen = new ColorClass('white');
    export let lime = new ColorClass('white');
    export let springgreen = new ColorClass('white');
    export let aqua = new ColorClass('white');
    export let cyan = new ColorClass('white');
    export let midnightblue = new ColorClass('white');
    export let dodgerblue = new ColorClass('white');
    export let lightseagreen = new ColorClass('white');
    export let forestgreen = new ColorClass('white');
    export let seagreen = new ColorClass('white');
    export let darkslategray = new ColorClass('white');
    export let limegreen = new ColorClass('white');
    export let mediumseagreen = new ColorClass('white');
    export let turquoise = new ColorClass('white');
    export let royalblue = new ColorClass('white');
    export let steelblue = new ColorClass('white');
    export let darkslateblue = new ColorClass('white');
    export let mediumturquoise = new ColorClass('white');
    export let indigo = new ColorClass('white');
    export let darkolivegreen = new ColorClass('white');
    export let cadetblue = new ColorClass('white');
    export let cornflowerblue = new ColorClass('white');
    export let rebeccapurple = new ColorClass('white');
    export let mediumaquamarine = new ColorClass('white');
    export let dimgray = new ColorClass('white');
    export let slateblue = new ColorClass('white');
    export let olivedrab = new ColorClass('white');
    export let slategray = new ColorClass('white');
    export let lightslategray = new ColorClass('white');
    export let mediumslateblue = new ColorClass('white');
    export let lawngreen = new ColorClass('white');
    export let chartreuse = new ColorClass('white');
    export let aquamarine = new ColorClass('white');
    export let maroon = new ColorClass('white');
    export let purple = new ColorClass('white');
    export let olive = new ColorClass('white');
    export let gray = new ColorClass('white');
    export let skyblue = new ColorClass('white');
    export let lightskyblue = new ColorClass('white');
    export let blueviolet = new ColorClass('white');
    export let darkred = new ColorClass('white');
    export let darkmagenta = new ColorClass('white');
    export let saddlebrown = new ColorClass('white');
    export let darkseagreen = new ColorClass('white');
    export let lightgreen = new ColorClass('white');
    export let mediumpurple = new ColorClass('white');
    export let darkviolet = new ColorClass('white');
    export let palegreen = new ColorClass('white');
    export let darkorchid = new ColorClass('white');
    export let yellowgreen = new ColorClass('white');
    export let sienna = new ColorClass('white');
    export let brown = new ColorClass('white');
    export let darkgray = new ColorClass('white');
    export let lightblue = new ColorClass('white');
    export let greenyellow = new ColorClass('white');
    export let paleturquoise = new ColorClass('white');
    export let lightsteelblue = new ColorClass('white');
    export let powderblue = new ColorClass('white');
    export let firebrick = new ColorClass('white');
    export let darkgoldenrod = new ColorClass('white');
    export let mediumorchid = new ColorClass('white');
    export let rosybrown = new ColorClass('white');
    export let darkkhaki = new ColorClass('white');
    export let silver = new ColorClass('white');
    export let mediumvioletred = new ColorClass('white');
    export let indianred = new ColorClass('white');
    export let peru = new ColorClass('white');
    export let chocolate = new ColorClass('white');
    export let tan = new ColorClass('white');
    export let lightgray = new ColorClass('white');
    export let thistle = new ColorClass('white');
    export let orchid = new ColorClass('white');
    export let goldenrod = new ColorClass('white');
    export let palevioletred = new ColorClass('white');
    export let crimson = new ColorClass('white');
    export let gainsboro = new ColorClass('white');
    export let plum = new ColorClass('white');
    export let burlywood = new ColorClass('white');
    export let lightcyan = new ColorClass('white');
    export let lavender = new ColorClass('white');
    export let darksalmon = new ColorClass('white');
    export let violet = new ColorClass('white');
    export let palegoldenrod = new ColorClass('white');
    export let lightcoral = new ColorClass('white');
    export let khaki = new ColorClass('white');
    export let aliceblue = new ColorClass('white');
    export let honeydew = new ColorClass('white');
    export let azure = new ColorClass('white');
    export let sandybrown = new ColorClass('white');
    export let wheat = new ColorClass('white');
    export let beige = new ColorClass('white');
    export let whitesmoke = new ColorClass('white');
    export let mintcream = new ColorClass('white');
    export let ghostwhite = new ColorClass('white');
    export let salmon = new ColorClass('white');
    export let antiquewhite = new ColorClass('white');
    export let linen = new ColorClass('white');
    export let lightgoldenrodyellow = new ColorClass('white');
    export let oldlace = new ColorClass('white');
    export let red = new ColorClass('white');
    export let fuchsia = new ColorClass('white');
    export let magenta = new ColorClass('white');
    export let deeppink = new ColorClass('white');
    export let orangered = new ColorClass('white');
    export let tomato = new ColorClass('white');
    export let hotpink = new ColorClass('white');
    export let coral = new ColorClass('white');
    export let darkorange = new ColorClass('white');
    export let lightsalmon = new ColorClass('white');
    export let orange = new ColorClass('white');
    export let lightpink = new ColorClass('white');
    export let pink = new ColorClass('white');
    export let gold = new ColorClass('white');
    export let peachpuff = new ColorClass('white');
    export let navajowhite = new ColorClass('white');
    export let moccasin = new ColorClass('white');
    export let bisque = new ColorClass('white');
    export let mistyrose = new ColorClass('white');
    export let blanchedalmond = new ColorClass('white');
    export let papayawhip = new ColorClass('white');
    export let lavenderblush = new ColorClass('white');
    export let seashell = new ColorClass('white');
    export let cornsilk = new ColorClass('white');
    export let lemonchiffon = new ColorClass('white');
    export let floralwhite = new ColorClass('white');
    export let snow = new ColorClass('white');
    export let yellow = new ColorClass('white');
    export let lightyellow = new ColorClass('white');
    export let ivory = new ColorClass('white');
    export let white = new ColorClass('white');

    export let blue50 = new ColorClass('#f5f9ff');
    export let blue100 = new ColorClass('#d0e1fd');
    export let blue200 = new ColorClass('#abc9fb');
    export let blue300 = new ColorClass('#85b2f9');
    export let blue400 = new ColorClass('#609af8');
    export let blue500 = new ColorClass('#3b82f6');
    export let blue600 = new ColorClass('#326fd1');
    export let blue700 = new ColorClass('#295bac');
    export let blue800 = new ColorClass('#204887');
    export let blue900 = new ColorClass('#183462');
    export let green50 = new ColorClass('#f4fcf7');
    export let green100 = new ColorClass('#caf1d8');
    export let green200 = new ColorClass('#a0e6ba');
    export let green300 = new ColorClass('#76db9b');
    export let green400 = new ColorClass('#4cd07d');
    export let green500 = new ColorClass('#22c55e');
    export let green600 = new ColorClass('#1da750');
    export let green700 = new ColorClass('#188a42');
    export let green800 = new ColorClass('#136c34');
    export let green900 = new ColorClass('#0e4f26');
    export let yellow50 = new ColorClass('#fefbf3');
    export let yellow100 = new ColorClass('#faedc4');
    export let yellow200 = new ColorClass('#f6de95');
    export let yellow300 = new ColorClass('#f2d066');
    export let yellow400 = new ColorClass('#eec137');
    export let yellow500 = new ColorClass('#eab308');
    export let yellow600 = new ColorClass('#c79807');
    export let yellow700 = new ColorClass('#a47d06');
    export let yellow800 = new ColorClass('#816204');
    export let yellow900 = new ColorClass('#5e4803');
    export let cyan50 = new ColorClass('#f3fbfd');
    export let cyan100 = new ColorClass('#c3edf5');
    export let cyan200 = new ColorClass('#94e0ed');
    export let cyan300 = new ColorClass('#65d2e4');
    export let cyan400 = new ColorClass('#35c4dc');
    export let cyan500 = new ColorClass('#06b6d4');
    export let cyan600 = new ColorClass('#059bb4');
    export let cyan700 = new ColorClass('#047f94');
    export let cyan800 = new ColorClass('#036475');
    export let cyan900 = new ColorClass('#024955');
    export let pink50 = new ColorClass('#fef6fa');
    export let pink100 = new ColorClass('#fad3e7');
    export let pink200 = new ColorClass('#f7b0d3');
    export let pink300 = new ColorClass('#f38ec0');
    export let pink400 = new ColorClass('#f06bac');
    export let pink500 = new ColorClass('#ec4899');
    export let pink600 = new ColorClass('#c93d82');
    export let pink700 = new ColorClass('#a5326b');
    export let pink800 = new ColorClass('#822854');
    export let pink900 = new ColorClass('#5e1d3d');
    export let indigo50 = new ColorClass('#f7f7fe');
    export let indigo100 = new ColorClass('#dadafc');
    export let indigo200 = new ColorClass('#bcbdf9');
    export let indigo300 = new ColorClass('#9ea0f6');
    export let indigo400 = new ColorClass('#8183f4');
    export let indigo500 = new ColorClass('#6366f1');
    export let indigo600 = new ColorClass('#5457cd');
    export let indigo700 = new ColorClass('#4547a9');
    export let indigo800 = new ColorClass('#363885');
    export let indigo900 = new ColorClass('#282960');
    export let teal50 = new ColorClass('#f3fbfb');
    export let teal100 = new ColorClass('#c7eeea');
    export let teal200 = new ColorClass('#9ae0d9');
    export let teal300 = new ColorClass('#6dd3c8');
    export let teal400 = new ColorClass('#41c5b7');
    export let teal500 = new ColorClass('#14b8a6');
    export let teal600 = new ColorClass('#119c8d');
    export let teal700 = new ColorClass('#0e8174');
    export let teal800 = new ColorClass('#0b655b');
    export let teal900 = new ColorClass('#084a42');
    export let orange50 = new ColorClass('#fff8f3');
    export let orange100 = new ColorClass('#feddc7');
    export let orange200 = new ColorClass('#fcc39b');
    export let orange300 = new ColorClass('#fba86f');
    export let orange400 = new ColorClass('#fa8e42');
    export let orange500 = new ColorClass('#f97316');
    export let orange600 = new ColorClass('#d46213');
    export let orange700 = new ColorClass('#ae510f');
    export let orange800 = new ColorClass('#893f0c');
    export let orange900 = new ColorClass('#642e09');
    export let bluegray50 = new ColorClass('#f7f8f9');
    export let bluegray100 = new ColorClass('#dadee3');
    export let bluegray200 = new ColorClass('#bcc3cd');
    export let bluegray300 = new ColorClass('#9fa9b7');
    export let bluegray400 = new ColorClass('#818ea1');
    export let bluegray500 = new ColorClass('#64748b');
    export let bluegray600 = new ColorClass('#556376');
    export let bluegray700 = new ColorClass('#465161');
    export let bluegray800 = new ColorClass('#37404c');
    export let bluegray900 = new ColorClass('#282e38');
    export let purple50 = new ColorClass('#fbf7ff');
    export let purple100 = new ColorClass('#ead6fd');
    export let purple200 = new ColorClass('#dab6fc');
    export let purple300 = new ColorClass('#c996fa');
    export let purple400 = new ColorClass('#b975f9');
    export let purple500 = new ColorClass('#a855f7');
    export let purple600 = new ColorClass('#8f48d2');
    export let purple700 = new ColorClass('#763cad');
    export let purple800 = new ColorClass('#5c2f88');
    export let purple900 = new ColorClass('#432263');
    export let red50 = new ColorClass('#fff5f5');
    export let red100 = new ColorClass('#ffd0ce');
    export let red200 = new ColorClass('#ffaca7');
    export let red300 = new ColorClass('#ff8780');
    export let red400 = new ColorClass('#ff6259');
    export let red500 = new ColorClass('#ff3d32');
    export let red600 = new ColorClass('#d9342b');
    export let red700 = new ColorClass('#b32b23');
    export let red800 = new ColorClass('#8c221c');
    export let red900 = new ColorClass('#661814');

    export let primary50 = new ColorClass('#f7f7fe');
    export let primary100 = new ColorClass('#dadafc');
    export let primary200 = new ColorClass('#bcbdf9');
    export let primary300 = new ColorClass('#9ea0f6');
    export let primary400 = new ColorClass('#8183f4');
    export let primary500 = new ColorClass('#6366f1');
    export let primary600 = new ColorClass('#5457cd');
    export let primary700 = new ColorClass('#4547a9');
    export let primary800 = new ColorClass('#363885');
    export let primary900 = new ColorClass('#282960');

    export let surfacea = new ColorClass('#ffffff');
    export let surfaceb = new ColorClass('#f8f9fa');
    export let surfacec = new ColorClass('#e9ecef');
    export let surfaced = new ColorClass('#dee2e6');
    export let surfacee = new ColorClass('#ffffff');
    export let surfacef = new ColorClass('#ffffff');
    export let textcolor = new ColorClass('#495057');
    export let textcolorsecondary = new ColorClass('#6c757d');
    export let primarycolor = new ColorClass('#6366F1');
    export let primarycolortext = new ColorClass('#ffffff');

    export let surface0 = new ColorClass('#ffffff');
    export let surface50 = new ColorClass('#FAFAFA');
    export let surface100 = new ColorClass('#F5F5F5');
    export let surface200 = new ColorClass('#EEEEEE');
    export let surface300 = new ColorClass('#E0E0E0');
    export let surface400 = new ColorClass('#BDBDBD');
    export let surface500 = new ColorClass('#9E9E9E');
    export let surface600 = new ColorClass('#757575');
    export let surface700 = new ColorClass('#616161');
    export let surface800 = new ColorClass('#424242');
    export let surface900 = new ColorClass('#212121');
    export let gray50 = new ColorClass('#FAFAFA');
    export let gray100 = new ColorClass('#F5F5F5');
    export let gray200 = new ColorClass('#EEEEEE');
    export let gray300 = new ColorClass('#E0E0E0');
    export let gray400 = new ColorClass('#BDBDBD');
    export let gray500 = new ColorClass('#9E9E9E');
    export let gray600 = new ColorClass('#757575');
    export let gray700 = new ColorClass('#616161');
    export let gray800 = new ColorClass('#424242');
    export let gray900 = new ColorClass('#212121');
    export let contentpadding = new ColorClass('1.25rem');
    export let inlinespacing = new ColorClass('0.5rem');
    export let borderradius = new ColorClass('6px;')
    export let surfaceground = new ColorClass('#eff3f8');
    export let surfacesection = new ColorClass('#ffffff');
    export let surfacecard = new ColorClass('#ffffff');
    export let surfaceoverlay = new ColorClass('#ffffff');
    export let surfaceborder = new ColorClass('#dfe7ef');
    export let surfacehover = new ColorClass('#f6f9fc');
}

Object.defineProperty(Color, 'black', { get: function () { return new ColorClass('#000000'); } });
Object.defineProperty(Color, 'navy', { get: function () { return new ColorClass('#000080'); } });
Object.defineProperty(Color, 'darkblue', { get: function () { return new ColorClass('#00008B'); } });
Object.defineProperty(Color, 'mediumblue', { get: function () { return new ColorClass('#0000CD'); } });
Object.defineProperty(Color, 'blue', { get: function () { return new ColorClass('#0000FF'); } });
Object.defineProperty(Color, 'darkgreen', { get: function () { return new ColorClass('#006400'); } });
Object.defineProperty(Color, 'green', { get: function () { return new ColorClass('#008000'); } });
Object.defineProperty(Color, 'teal', { get: function () { return new ColorClass('#008080'); } });
Object.defineProperty(Color, 'darkcyan', { get: function () { return new ColorClass('#008B8B'); } });
Object.defineProperty(Color, 'deepskyblue', { get: function () { return new ColorClass('#00BFFF'); } });
Object.defineProperty(Color, 'darkturquoise', { get: function () { return new ColorClass('#00CED1'); } });
Object.defineProperty(Color, 'mediumspringgreen', { get: function () { return new ColorClass('#00FA9A'); } });
Object.defineProperty(Color, 'lime', { get: function () { return new ColorClass('#00FF00'); } });
Object.defineProperty(Color, 'springgreen', { get: function () { return new ColorClass('#00FF7F'); } });
Object.defineProperty(Color, 'aqua', { get: function () { return new ColorClass('#00FFFF'); } });
Object.defineProperty(Color, 'cyan', { get: function () { return new ColorClass('#00FFFF'); } });
Object.defineProperty(Color, 'midnightblue', { get: function () { return new ColorClass('#191970'); } });
Object.defineProperty(Color, 'dodgerblue', { get: function () { return new ColorClass('#1E90FF'); } });
Object.defineProperty(Color, 'lightseagreen', { get: function () { return new ColorClass('#20B2AA'); } });
Object.defineProperty(Color, 'forestgreen', { get: function () { return new ColorClass('#228B22'); } });
Object.defineProperty(Color, 'seagreen', { get: function () { return new ColorClass('#2E8B57'); } });
Object.defineProperty(Color, 'darkslategray', { get: function () { return new ColorClass('#2F4F4F'); } });
Object.defineProperty(Color, 'limegreen', { get: function () { return new ColorClass('#32CD32'); } });
Object.defineProperty(Color, 'mediumseagreen', { get: function () { return new ColorClass('#3CB371'); } });
Object.defineProperty(Color, 'turquoise', { get: function () { return new ColorClass('#40E0D0'); } });
Object.defineProperty(Color, 'royalblue', { get: function () { return new ColorClass('#4169E1'); } });
Object.defineProperty(Color, 'steelblue', { get: function () { return new ColorClass('#4682B4'); } });
Object.defineProperty(Color, 'darkslateblue', { get: function () { return new ColorClass('#483D8B'); } });
Object.defineProperty(Color, 'mediumturquoise', { get: function () { return new ColorClass('#48D1CC'); } });
Object.defineProperty(Color, 'indigo', { get: function () { return new ColorClass('#4B0082'); } });
Object.defineProperty(Color, 'darkolivegreen', { get: function () { return new ColorClass('#556B2F'); } });
Object.defineProperty(Color, 'cadetblue', { get: function () { return new ColorClass('#5F9EA0'); } });
Object.defineProperty(Color, 'cornflowerblue', { get: function () { return new ColorClass('#6495ED'); } });
Object.defineProperty(Color, 'rebeccapurple', { get: function () { return new ColorClass('#663399'); } });
Object.defineProperty(Color, 'mediumaquamarine', { get: function () { return new ColorClass('#66CDAA'); } });
Object.defineProperty(Color, 'dimgray', { get: function () { return new ColorClass('#696969'); } });
Object.defineProperty(Color, 'slateblue', { get: function () { return new ColorClass('#6A5ACD'); } });
Object.defineProperty(Color, 'olivedrab', { get: function () { return new ColorClass('#6B8E23'); } });
Object.defineProperty(Color, 'slategray', { get: function () { return new ColorClass('#708090'); } });
Object.defineProperty(Color, 'lightslategray', { get: function () { return new ColorClass('#778899'); } });
Object.defineProperty(Color, 'mediumslateblue', { get: function () { return new ColorClass('#7B68EE'); } });
Object.defineProperty(Color, 'lawngreen', { get: function () { return new ColorClass('#7CFC00'); } });
Object.defineProperty(Color, 'chartreuse', { get: function () { return new ColorClass('#7FFF00'); } });
Object.defineProperty(Color, 'aquamarine', { get: function () { return new ColorClass('#7FFFD4'); } });
Object.defineProperty(Color, 'maroon', { get: function () { return new ColorClass('#800000'); } });
Object.defineProperty(Color, 'purple', { get: function () { return new ColorClass('#800080'); } });
Object.defineProperty(Color, 'olive', { get: function () { return new ColorClass('#808000'); } });
Object.defineProperty(Color, 'gray', { get: function () { return new ColorClass('#808080'); } });
Object.defineProperty(Color, 'skyblue', { get: function () { return new ColorClass('#87CEEB'); } });
Object.defineProperty(Color, 'lightskyblue', { get: function () { return new ColorClass('#87CEFA'); } });
Object.defineProperty(Color, 'blueviolet', { get: function () { return new ColorClass('#8A2BE2'); } });
Object.defineProperty(Color, 'darkred', { get: function () { return new ColorClass('#8B0000'); } });
Object.defineProperty(Color, 'darkmagenta', { get: function () { return new ColorClass('#8B008B'); } });
Object.defineProperty(Color, 'saddlebrown', { get: function () { return new ColorClass('#8B4513'); } });
Object.defineProperty(Color, 'darkseagreen', { get: function () { return new ColorClass('#8FBC8F'); } });
Object.defineProperty(Color, 'lightgreen', { get: function () { return new ColorClass('#90EE90'); } });
Object.defineProperty(Color, 'mediumpurple', { get: function () { return new ColorClass('#9370DB'); } });
Object.defineProperty(Color, 'darkviolet', { get: function () { return new ColorClass('#9400D3'); } });
Object.defineProperty(Color, 'palegreen', { get: function () { return new ColorClass('#98FB98'); } });
Object.defineProperty(Color, 'darkorchid', { get: function () { return new ColorClass('#9932CC'); } });
Object.defineProperty(Color, 'yellowgreen', { get: function () { return new ColorClass('#9ACD32'); } });
Object.defineProperty(Color, 'sienna', { get: function () { return new ColorClass('#A0522D'); } });
Object.defineProperty(Color, 'brown', { get: function () { return new ColorClass('#A52A2A'); } });
Object.defineProperty(Color, 'darkgray', { get: function () { return new ColorClass('#A9A9A9'); } });
Object.defineProperty(Color, 'lightblue', { get: function () { return new ColorClass('#ADD8E6'); } });
Object.defineProperty(Color, 'greenyellow', { get: function () { return new ColorClass('#ADFF2F'); } });
Object.defineProperty(Color, 'paleturquoise', { get: function () { return new ColorClass('#AFEEEE'); } });
Object.defineProperty(Color, 'lightsteelblue', { get: function () { return new ColorClass('#B0C4DE'); } });
Object.defineProperty(Color, 'powderblue', { get: function () { return new ColorClass('#B0E0E6'); } });
Object.defineProperty(Color, 'firebrick', { get: function () { return new ColorClass('#B22222'); } });
Object.defineProperty(Color, 'darkgoldenrod', { get: function () { return new ColorClass('#B8860B'); } });
Object.defineProperty(Color, 'mediumorchid', { get: function () { return new ColorClass('#BA55D3'); } });
Object.defineProperty(Color, 'rosybrown', { get: function () { return new ColorClass('#BC8F8F'); } });
Object.defineProperty(Color, 'darkkhaki', { get: function () { return new ColorClass('#BDB76B'); } });
Object.defineProperty(Color, 'silver', { get: function () { return new ColorClass('#C0C0C0'); } });
Object.defineProperty(Color, 'mediumvioletred', { get: function () { return new ColorClass('#C71585'); } });
Object.defineProperty(Color, 'indianred', { get: function () { return new ColorClass('#CD5C5C'); } });
Object.defineProperty(Color, 'peru', { get: function () { return new ColorClass('#CD853F'); } });
Object.defineProperty(Color, 'chocolate', { get: function () { return new ColorClass('#D2691E'); } });
Object.defineProperty(Color, 'tan', { get: function () { return new ColorClass('#D2B48C'); } });
Object.defineProperty(Color, 'lightgray', { get: function () { return new ColorClass('#D3D3D3'); } });
Object.defineProperty(Color, 'thistle', { get: function () { return new ColorClass('#D8BFD8'); } });
Object.defineProperty(Color, 'orchid', { get: function () { return new ColorClass('#DA70D6'); } });
Object.defineProperty(Color, 'goldenrod', { get: function () { return new ColorClass('#DAA520'); } });
Object.defineProperty(Color, 'palevioletred', { get: function () { return new ColorClass('#DB7093'); } });
Object.defineProperty(Color, 'crimson', { get: function () { return new ColorClass('#DC143C'); } });
Object.defineProperty(Color, 'gainsboro', { get: function () { return new ColorClass('#DCDCDC'); } });
Object.defineProperty(Color, 'plum', { get: function () { return new ColorClass('#DDA0DD'); } });
Object.defineProperty(Color, 'burlywood', { get: function () { return new ColorClass('#DEB887'); } });
Object.defineProperty(Color, 'lightcyan', { get: function () { return new ColorClass('#E0FFFF'); } });
Object.defineProperty(Color, 'lavender', { get: function () { return new ColorClass('#E6E6FA'); } });
Object.defineProperty(Color, 'darksalmon', { get: function () { return new ColorClass('#E9967A'); } });
Object.defineProperty(Color, 'violet', { get: function () { return new ColorClass('#EE82EE'); } });
Object.defineProperty(Color, 'palegoldenrod', { get: function () { return new ColorClass('#EEE8AA'); } });
Object.defineProperty(Color, 'lightcoral', { get: function () { return new ColorClass('#F08080'); } });
Object.defineProperty(Color, 'khaki', { get: function () { return new ColorClass('#F0E68C'); } });
Object.defineProperty(Color, 'aliceblue', { get: function () { return new ColorClass('#F0F8FF'); } });
Object.defineProperty(Color, 'honeydew', { get: function () { return new ColorClass('#F0FFF0'); } });
Object.defineProperty(Color, 'azure', { get: function () { return new ColorClass('#F0FFFF'); } });
Object.defineProperty(Color, 'sandybrown', { get: function () { return new ColorClass('#F4A460'); } });
Object.defineProperty(Color, 'wheat', { get: function () { return new ColorClass('#F5DEB3'); } });
Object.defineProperty(Color, 'beige', { get: function () { return new ColorClass('#F5F5DC'); } });
Object.defineProperty(Color, 'whitesmoke', { get: function () { return new ColorClass('#F5F5F5'); } });
Object.defineProperty(Color, 'mintcream', { get: function () { return new ColorClass('#F5FFFA'); } });
Object.defineProperty(Color, 'ghostwhite', { get: function () { return new ColorClass('#F8F8FF'); } });
Object.defineProperty(Color, 'salmon', { get: function () { return new ColorClass('#FA8072'); } });
Object.defineProperty(Color, 'antiquewhite', { get: function () { return new ColorClass('#FAEBD7'); } });
Object.defineProperty(Color, 'linen', { get: function () { return new ColorClass('#FAF0E6'); } });
Object.defineProperty(Color, 'lightgoldenrodyellow', { get: function () { return new ColorClass('#FAFAD2'); } });
Object.defineProperty(Color, 'oldlace', { get: function () { return new ColorClass('#FDF5E6'); } });
Object.defineProperty(Color, 'red', { get: function () { return new ColorClass('#FF0000'); } });
Object.defineProperty(Color, 'fuchsia', { get: function () { return new ColorClass('#FF00FF'); } });
Object.defineProperty(Color, 'magenta', { get: function () { return new ColorClass('#FF00FF'); } });
Object.defineProperty(Color, 'deeppink', { get: function () { return new ColorClass('#FF1493'); } });
Object.defineProperty(Color, 'orangered', { get: function () { return new ColorClass('#FF4500'); } });
Object.defineProperty(Color, 'tomato', { get: function () { return new ColorClass('#FF6347'); } });
Object.defineProperty(Color, 'hotpink', { get: function () { return new ColorClass('#FF69B4'); } });
Object.defineProperty(Color, 'coral', { get: function () { return new ColorClass('#FF7F50'); } });
Object.defineProperty(Color, 'darkorange', { get: function () { return new ColorClass('#FF8C00'); } });
Object.defineProperty(Color, 'lightsalmon', { get: function () { return new ColorClass('#FFA07A'); } });
Object.defineProperty(Color, 'orange', { get: function () { return new ColorClass('#FFA500'); } });
Object.defineProperty(Color, 'lightpink', { get: function () { return new ColorClass('#FFB6C1'); } });
Object.defineProperty(Color, 'pink', { get: function () { return new ColorClass('#FFC0CB'); } });
Object.defineProperty(Color, 'gold', { get: function () { return new ColorClass('#FFD700'); } });
Object.defineProperty(Color, 'peachpuff', { get: function () { return new ColorClass('#FFDAB9'); } });
Object.defineProperty(Color, 'navajowhite', { get: function () { return new ColorClass('#FFDEAD'); } });
Object.defineProperty(Color, 'moccasin', { get: function () { return new ColorClass('#FFE4B5'); } });
Object.defineProperty(Color, 'bisque', { get: function () { return new ColorClass('#FFE4C4'); } });
Object.defineProperty(Color, 'mistyrose', { get: function () { return new ColorClass('#FFE4E1'); } });
Object.defineProperty(Color, 'blanchedalmond', { get: function () { return new ColorClass('#FFEBCD'); } });
Object.defineProperty(Color, 'papayawhip', { get: function () { return new ColorClass('#FFEFD5'); } });
Object.defineProperty(Color, 'lavenderblush', { get: function () { return new ColorClass('#FFF0F5'); } });
Object.defineProperty(Color, 'seashell', { get: function () { return new ColorClass('#FFF5EE'); } });
Object.defineProperty(Color, 'cornsilk', { get: function () { return new ColorClass('#FFF8DC'); } });
Object.defineProperty(Color, 'lemonchiffon', { get: function () { return new ColorClass('#FFFACD'); } });
Object.defineProperty(Color, 'floralwhite', { get: function () { return new ColorClass('#FFFAF0'); } });
Object.defineProperty(Color, 'snow', { get: function () { return new ColorClass('#FFFAFA'); } });
Object.defineProperty(Color, 'yellow', { get: function () { return new ColorClass('#FFFF00'); } });
Object.defineProperty(Color, 'lightyellow', { get: function () { return new ColorClass('#FFFFE0'); } });
Object.defineProperty(Color, 'ivory', { get: function () { return new ColorClass('#FFFFF0'); } });
Object.defineProperty(Color, 'white', { get: function () { return new ColorClass('#FFFFFF'); } });

Object.defineProperty(Color, 'blue50', { get: function () { return new ColorClass('#f5f9ff'); } });
Object.defineProperty(Color, 'blue100', { get: function () { return new ColorClass('#d0e1fd'); } });
Object.defineProperty(Color, 'blue200', { get: function () { return new ColorClass('#abc9fb'); } });
Object.defineProperty(Color, 'blue300', { get: function () { return new ColorClass('#85b2f9'); } });
Object.defineProperty(Color, 'blue400', { get: function () { return new ColorClass('#609af8'); } });
Object.defineProperty(Color, 'blue500', { get: function () { return new ColorClass('#3b82f6'); } });
Object.defineProperty(Color, 'blue600', { get: function () { return new ColorClass('#326fd1'); } });
Object.defineProperty(Color, 'blue700', { get: function () { return new ColorClass('#295bac'); } });
Object.defineProperty(Color, 'blue800', { get: function () { return new ColorClass('#204887'); } });
Object.defineProperty(Color, 'blue900', { get: function () { return new ColorClass('#183462'); } });
Object.defineProperty(Color, 'green50', { get: function () { return new ColorClass('#f4fcf7'); } });
Object.defineProperty(Color, 'green100', { get: function () { return new ColorClass('#caf1d8'); } });
Object.defineProperty(Color, 'green200', { get: function () { return new ColorClass('#a0e6ba'); } });
Object.defineProperty(Color, 'green300', { get: function () { return new ColorClass('#76db9b'); } });
Object.defineProperty(Color, 'green400', { get: function () { return new ColorClass('#4cd07d'); } });
Object.defineProperty(Color, 'green500', { get: function () { return new ColorClass('#22c55e'); } });
Object.defineProperty(Color, 'green600', { get: function () { return new ColorClass('#1da750'); } });
Object.defineProperty(Color, 'green700', { get: function () { return new ColorClass('#188a42'); } });
Object.defineProperty(Color, 'green800', { get: function () { return new ColorClass('#136c34'); } });
Object.defineProperty(Color, 'green900', { get: function () { return new ColorClass('#0e4f26'); } });
Object.defineProperty(Color, 'yellow50', { get: function () { return new ColorClass('#fefbf3'); } });
Object.defineProperty(Color, 'yellow100', { get: function () { return new ColorClass('#faedc4'); } });
Object.defineProperty(Color, 'yellow200', { get: function () { return new ColorClass('#f6de95'); } });
Object.defineProperty(Color, 'yellow300', { get: function () { return new ColorClass('#f2d066'); } });
Object.defineProperty(Color, 'yellow400', { get: function () { return new ColorClass('#eec137'); } });
Object.defineProperty(Color, 'yellow500', { get: function () { return new ColorClass('#eab308'); } });
Object.defineProperty(Color, 'yellow600', { get: function () { return new ColorClass('#c79807'); } });
Object.defineProperty(Color, 'yellow700', { get: function () { return new ColorClass('#a47d06'); } });
Object.defineProperty(Color, 'yellow800', { get: function () { return new ColorClass('#816204'); } });
Object.defineProperty(Color, 'yellow900', { get: function () { return new ColorClass('#5e4803'); } });
Object.defineProperty(Color, 'cyan50', { get: function () { return new ColorClass('#f3fbfd'); } });
Object.defineProperty(Color, 'cyan100', { get: function () { return new ColorClass('#c3edf5'); } });
Object.defineProperty(Color, 'cyan200', { get: function () { return new ColorClass('#94e0ed'); } });
Object.defineProperty(Color, 'cyan300', { get: function () { return new ColorClass('#65d2e4'); } });
Object.defineProperty(Color, 'cyan400', { get: function () { return new ColorClass('#35c4dc'); } });
Object.defineProperty(Color, 'cyan500', { get: function () { return new ColorClass('#06b6d4'); } });
Object.defineProperty(Color, 'cyan600', { get: function () { return new ColorClass('#059bb4'); } });
Object.defineProperty(Color, 'cyan700', { get: function () { return new ColorClass('#047f94'); } });
Object.defineProperty(Color, 'cyan800', { get: function () { return new ColorClass('#036475'); } });
Object.defineProperty(Color, 'cyan900', { get: function () { return new ColorClass('#024955'); } });
Object.defineProperty(Color, 'pink50', { get: function () { return new ColorClass('#fef6fa'); } });
Object.defineProperty(Color, 'pink100', { get: function () { return new ColorClass('#fad3e7'); } });
Object.defineProperty(Color, 'pink200', { get: function () { return new ColorClass('#f7b0d3'); } });
Object.defineProperty(Color, 'pink300', { get: function () { return new ColorClass('#f38ec0'); } });
Object.defineProperty(Color, 'pink400', { get: function () { return new ColorClass('#f06bac'); } });
Object.defineProperty(Color, 'pink500', { get: function () { return new ColorClass('#ec4899'); } });
Object.defineProperty(Color, 'pink600', { get: function () { return new ColorClass('#c93d82'); } });
Object.defineProperty(Color, 'pink700', { get: function () { return new ColorClass('#a5326b'); } });
Object.defineProperty(Color, 'pink800', { get: function () { return new ColorClass('#822854'); } });
Object.defineProperty(Color, 'pink900', { get: function () { return new ColorClass('#5e1d3d'); } });
Object.defineProperty(Color, 'indigo50', { get: function () { return new ColorClass('#f7f7fe'); } });
Object.defineProperty(Color, 'indigo100', { get: function () { return new ColorClass('#dadafc'); } });
Object.defineProperty(Color, 'indigo200', { get: function () { return new ColorClass('#bcbdf9'); } });
Object.defineProperty(Color, 'indigo300', { get: function () { return new ColorClass('#9ea0f6'); } });
Object.defineProperty(Color, 'indigo400', { get: function () { return new ColorClass('#8183f4'); } });
Object.defineProperty(Color, 'indigo500', { get: function () { return new ColorClass('#6366f1'); } });
Object.defineProperty(Color, 'indigo600', { get: function () { return new ColorClass('#5457cd'); } });
Object.defineProperty(Color, 'indigo700', { get: function () { return new ColorClass('#4547a9'); } });
Object.defineProperty(Color, 'indigo800', { get: function () { return new ColorClass('#363885'); } });
Object.defineProperty(Color, 'indigo900', { get: function () { return new ColorClass('#282960'); } });
Object.defineProperty(Color, 'teal50', { get: function () { return new ColorClass('#f3fbfb'); } });
Object.defineProperty(Color, 'teal100', { get: function () { return new ColorClass('#c7eeea'); } });
Object.defineProperty(Color, 'teal200', { get: function () { return new ColorClass('#9ae0d9'); } });
Object.defineProperty(Color, 'teal300', { get: function () { return new ColorClass('#6dd3c8'); } });
Object.defineProperty(Color, 'teal400', { get: function () { return new ColorClass('#41c5b7'); } });
Object.defineProperty(Color, 'teal500', { get: function () { return new ColorClass('#14b8a6'); } });
Object.defineProperty(Color, 'teal600', { get: function () { return new ColorClass('#119c8d'); } });
Object.defineProperty(Color, 'teal700', { get: function () { return new ColorClass('#0e8174'); } });
Object.defineProperty(Color, 'teal800', { get: function () { return new ColorClass('#0b655b'); } });
Object.defineProperty(Color, 'teal900', { get: function () { return new ColorClass('#084a42'); } });
Object.defineProperty(Color, 'orange50', { get: function () { return new ColorClass('#fff8f3'); } });
Object.defineProperty(Color, 'orange100', { get: function () { return new ColorClass('#feddc7'); } });
Object.defineProperty(Color, 'orange200', { get: function () { return new ColorClass('#fcc39b'); } });
Object.defineProperty(Color, 'orange300', { get: function () { return new ColorClass('#fba86f'); } });
Object.defineProperty(Color, 'orange400', { get: function () { return new ColorClass('#fa8e42'); } });
Object.defineProperty(Color, 'orange500', { get: function () { return new ColorClass('#f97316'); } });
Object.defineProperty(Color, 'orange600', { get: function () { return new ColorClass('#d46213'); } });
Object.defineProperty(Color, 'orange700', { get: function () { return new ColorClass('#ae510f'); } });
Object.defineProperty(Color, 'orange800', { get: function () { return new ColorClass('#893f0c'); } });
Object.defineProperty(Color, 'orange900', { get: function () { return new ColorClass('#642e09'); } });
Object.defineProperty(Color, 'bluegray50', { get: function () { return new ColorClass('#f7f8f9'); } });
Object.defineProperty(Color, 'bluegray100', { get: function () { return new ColorClass('#dadee3'); } });
Object.defineProperty(Color, 'bluegray200', { get: function () { return new ColorClass('#bcc3cd'); } });
Object.defineProperty(Color, 'bluegray300', { get: function () { return new ColorClass('#9fa9b7'); } });
Object.defineProperty(Color, 'bluegray400', { get: function () { return new ColorClass('#818ea1'); } });
Object.defineProperty(Color, 'bluegray500', { get: function () { return new ColorClass('#64748b'); } });
Object.defineProperty(Color, 'bluegray600', { get: function () { return new ColorClass('#556376'); } });
Object.defineProperty(Color, 'bluegray700', { get: function () { return new ColorClass('#465161'); } });
Object.defineProperty(Color, 'bluegray800', { get: function () { return new ColorClass('#37404c'); } });
Object.defineProperty(Color, 'bluegray900', { get: function () { return new ColorClass('#282e38'); } });
Object.defineProperty(Color, 'purple50', { get: function () { return new ColorClass('#fbf7ff'); } });
Object.defineProperty(Color, 'purple100', { get: function () { return new ColorClass('#ead6fd'); } });
Object.defineProperty(Color, 'purple200', { get: function () { return new ColorClass('#dab6fc'); } });
Object.defineProperty(Color, 'purple300', { get: function () { return new ColorClass('#c996fa'); } });
Object.defineProperty(Color, 'purple400', { get: function () { return new ColorClass('#b975f9'); } });
Object.defineProperty(Color, 'purple500', { get: function () { return new ColorClass('#a855f7'); } });
Object.defineProperty(Color, 'purple600', { get: function () { return new ColorClass('#8f48d2'); } });
Object.defineProperty(Color, 'purple700', { get: function () { return new ColorClass('#763cad'); } });
Object.defineProperty(Color, 'purple800', { get: function () { return new ColorClass('#5c2f88'); } });
Object.defineProperty(Color, 'purple900', { get: function () { return new ColorClass('#432263'); } });
Object.defineProperty(Color, 'red50', { get: function () { return new ColorClass('#fff5f5'); } });
Object.defineProperty(Color, 'red100', { get: function () { return new ColorClass('#ffd0ce'); } });
Object.defineProperty(Color, 'red200', { get: function () { return new ColorClass('#ffaca7'); } });
Object.defineProperty(Color, 'red300', { get: function () { return new ColorClass('#ff8780'); } });
Object.defineProperty(Color, 'red400', { get: function () { return new ColorClass('#ff6259'); } });
Object.defineProperty(Color, 'red500', { get: function () { return new ColorClass('#ff3d32'); } });
Object.defineProperty(Color, 'red600', { get: function () { return new ColorClass('#d9342b'); } });
Object.defineProperty(Color, 'red700', { get: function () { return new ColorClass('#b32b23'); } });
Object.defineProperty(Color, 'red800', { get: function () { return new ColorClass('#8c221c'); } });
Object.defineProperty(Color, 'red900', { get: function () { return new ColorClass('#661814'); } });
Object.defineProperty(Color, 'primary50', { get: function () { return new ColorClass('#f7f7fe'); } });
Object.defineProperty(Color, 'primary100', { get: function () { return new ColorClass('#dadafc'); } });
Object.defineProperty(Color, 'primary200', { get: function () { return new ColorClass('#bcbdf9'); } });
Object.defineProperty(Color, 'primary300', { get: function () { return new ColorClass('#9ea0f6'); } });
Object.defineProperty(Color, 'primary400', { get: function () { return new ColorClass('#8183f4'); } });
Object.defineProperty(Color, 'primary500', { get: function () { return new ColorClass('#6366f1'); } });
Object.defineProperty(Color, 'primary600', { get: function () { return new ColorClass('#5457cd'); } });
Object.defineProperty(Color, 'primary700', { get: function () { return new ColorClass('#4547a9'); } });
Object.defineProperty(Color, 'primary800', { get: function () { return new ColorClass('#363885'); } });
Object.defineProperty(Color, 'primary900', { get: function () { return new ColorClass('#282960'); } });


Object.defineProperty(Color, 'surfacea', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'surfaceb', { get: function () { new ColorClass('#f8f9fa') } });
Object.defineProperty(Color, 'surfacec', { get: function () { new ColorClass('#e9ecef') } });
Object.defineProperty(Color, 'surfaced', { get: function () { new ColorClass('#dee2e6') } });
Object.defineProperty(Color, 'surfacee', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'surfacef', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'textcolor', { get: function () { new ColorClass('#495057') } });
Object.defineProperty(Color, 'textcolorsecondary', { get: function () { new ColorClass('#6c757d') } });
Object.defineProperty(Color, 'primarycolor', { get: function () { new ColorClass('#6366F1') } });
Object.defineProperty(Color, 'primarycolortext', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'surface0', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'surface50', { get: function () { new ColorClass('#FAFAFA') } });
Object.defineProperty(Color, 'surface100', { get: function () { new ColorClass('#F5F5F5') } });
Object.defineProperty(Color, 'surface200', { get: function () { new ColorClass('#EEEEEE') } });
Object.defineProperty(Color, 'surface300', { get: function () { new ColorClass('#E0E0E0') } });
Object.defineProperty(Color, 'surface400', { get: function () { new ColorClass('#BDBDBD') } });
Object.defineProperty(Color, 'surface500', { get: function () { new ColorClass('#9E9E9E') } });
Object.defineProperty(Color, 'surface600', { get: function () { new ColorClass('#757575') } });
Object.defineProperty(Color, 'surface700', { get: function () { new ColorClass('#616161') } });
Object.defineProperty(Color, 'surface800', { get: function () { new ColorClass('#424242') } });
Object.defineProperty(Color, 'surface900', { get: function () { new ColorClass('#212121') } });
Object.defineProperty(Color, 'gray50', { get: function () { new ColorClass('#FAFAFA') } });
Object.defineProperty(Color, 'gray100', { get: function () { new ColorClass('#F5F5F5') } });
Object.defineProperty(Color, 'gray200', { get: function () { new ColorClass('#EEEEEE') } });
Object.defineProperty(Color, 'gray300', { get: function () { new ColorClass('#E0E0E0') } });
Object.defineProperty(Color, 'gray400', { get: function () { new ColorClass('#BDBDBD') } });
Object.defineProperty(Color, 'gray500', { get: function () { new ColorClass('#9E9E9E') } });
Object.defineProperty(Color, 'gray600', { get: function () { new ColorClass('#757575') } });
Object.defineProperty(Color, 'gray700', { get: function () { new ColorClass('#616161') } });
Object.defineProperty(Color, 'gray800', { get: function () { new ColorClass('#424242') } });
Object.defineProperty(Color, 'gray900', { get: function () { new ColorClass('#212121') } });

Object.defineProperty(Color, 'surfaceground', { get: function () { new ColorClass('#eff3f8') } });
Object.defineProperty(Color, 'surfacesection', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'surfacecard', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'surfaceoverlay', { get: function () { new ColorClass('#ffffff') } });
Object.defineProperty(Color, 'surfaceborder', { get: function () { new ColorClass('#dfe7ef') } });
Object.defineProperty(Color, 'surfacehover', { get: function () { new ColorClass('#f6f9fc') } });

