export const NativeCultures = {
    "Invariant":
    {
        Locale: "",
        LCID: "0x7f",
        LOCALE_SNAME: "",
        LOCALE_SPARENT: "",
        LOCALE_SDURATION: "hh:mm:ss",
        LOCALE_SKEYBOARDSTOINSTALL: "0409:00000409",
        LOCALE_SSHORTESTDAYNAME1: "Mo",
        LOCALE_SSHORTESTDAYNAME2: "Tu",
        LOCALE_SSHORTESTDAYNAME3: "We",
        LOCALE_SSHORTESTDAYNAME4: "Th",
        LOCALE_SSHORTESTDAYNAME5: "Fr",
        LOCALE_SSHORTESTDAYNAME6: "Sa",
        LOCALE_SSHORTESTDAYNAME7: "Su",
        LOCALE_SISO639LANGNAME2: "ivl",
        LOCALE_SISO3166CTRYNAME2: "",
        LOCALE_SNAN: "NaN",
        LOCALE_SPOSINFINITY: "Infinity",
        LOCALE_SNEGINFINITY: "-Infinity",
        LOCALE_SSCRIPTS: "Latn;",
        LOCALE_IDATE: "0",
        LOCALE_SDECIMAL: ".",
        LOCALE_SLOCALIZEDCOUNTRYNAME: "Invariant Country",
        LOCALE_ALLOW_NEUTRAL_NAMES: "error 1004",
        LOCALE_ALTERNATE_SORTS: "Invariant Language",
        LOCALE_CUSTOM_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UI_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UNSPECIFIED: "error 1004",
        LOCALE_ICALENDARTYPE: "1",
        LOCALE_ICENTURY: "1",
        LOCALE_IDIALINGCODE: "1",
        LOCALE_ICOUNTRY: "1",
        LOCALE_ICURRDIGITS: "2",
        LOCALE_ICURRENCY: "0",
        LOCALE_IDAYLZERO: "1",
        LOCALE_IDEFAULTANSICODEPAGE: "1252",
        LOCALE_IDEFAULTCODEPAGE: "437",
        LOCALE_IDEFAULTCOUNTRY: "1",
        LOCALE_IDEFAULTEBCDICCODEPAGE: "037",
        LOCALE_IDEFAULTLANGUAGE: "0409",
        LOCALE_IDEFAULTMACCODEPAGE: "10000",
        LOCALE_IDIGITS: "2",
        LOCALE_IDIGITSUBSTITUTION: "1",
        LOCALE_IFIRSTDAYOFWEEK: "6",
        LOCALE_IFIRSTWEEKOFYEAR: "0",
        LOCALE_IGEOID: "244",
        LOCALE_IINTLCURRDIGITS: "2",
        LOCALE_ILANGUAGE: "007f",
        LOCALE_ILDATE: "1",
        LOCALE_ILZERO: "1",
        LOCALE_IMEASURE: "0",
        LOCALE_IMONLZERO: "1",
        LOCALE_INEGATIVEPERCENT: "0",
        LOCALE_INEGCURR: "0",
        LOCALE_INEGNUMBER: "1",
        LOCALE_INEGSEPBYSPACE: "0",
        LOCALE_INEGSIGNPOSN: "0",
        LOCALE_INEGSYMPRECEDES: "1",
        LOCALE_INEUTRAL: "0",
        LOCALE_INVARIANT: "p",
        LOCALE_IOPTIONALCALENDAR: "0",
        LOCALE_IPAPERSIZE: "9",
        LOCALE_IPOSITIVEPERCENT: "0",
        LOCALE_IPOSSEPBYSPACE: "0",
        LOCALE_IPOSSIGNPOSN: "3",
        LOCALE_IPOSSYMPRECEDES: "1",
        LOCALE_IREADINGLAYOUT: "0",
        LOCALE_ITIME: "1",
        LOCALE_ITIMEMARKPOSN: "0",
        LOCALE_ITLZERO: "1",
        LOCALE_NEUTRAL: "error 1004",
        LOCALE_NEUTRALDATA: "3;0",
        LOCALE_REPLACEMENT: "Invariant Country",
        LOCALE_SCOUNTRY: "Invariant Country",
        LOCALE_SCURRENCY: "¤",
        LOCALE_SDATE: "/",
        LOCALE_SDAYNAME1: "Monday",
        LOCALE_SDAYNAME2: "Tuesday",
        LOCALE_SDAYNAME3: "Wednesday",
        LOCALE_SDAYNAME4: "Thursday",
        LOCALE_SDAYNAME5: "Friday",
        LOCALE_SDAYNAME6: "Saturday",
        LOCALE_SDAYNAME7: "Sunday",
        LOCALE_SENGLISHCOUNTRYNAME: "Invariant Country",
        LOCALE_SENGLISHDISPLAYNAME: "Invariant Language (Invariant Country)",
        LOCALE_SENGLISHLANGUAGENAME: "Invariant Language",
        LOCALE_SGROUPING: "3;0",
        LOCALE_SINTLSYMBOL: "XDR",
        LOCALE_SISO3166CTRYNAME: "IV",
        LOCALE_SISO639LANGNAME: "iv",
        LOCALE_SLANGDISPLAYNAME: "Invariant Language",
        LOCALE_SLANGUAGE: "Invariant Language (Invariant Country)",
        LOCALE_SLIST: ",",
        LOCALE_SLOCALIZEDDISPLAYNAME: "Invariant Language (Invariant Country)",
        LOCALE_SLOCALIZEDLANGUAGENAME: "Invariant Language",
        LOCALE_SLONGDATE: "dddd, dd MMMM yyyy",
        LOCALE_SMONDECIMALSEP: ".",
        LOCALE_SMONGROUPING: "3;0",
        LOCALE_SMONTHOUSANDSEP: ",",
        LOCALE_SMONTHDAY: "MMMM dd",
        LOCALE_SMONTHNAME1: "January",
        LOCALE_SMONTHNAME2: "February",
        LOCALE_SMONTHNAME3: "March",
        LOCALE_SMONTHNAME4: "April",
        LOCALE_SMONTHNAME5: "May",
        LOCALE_SMONTHNAME6: "June",
        LOCALE_SMONTHNAME7: "July",
        LOCALE_SMONTHNAME8: "August",
        LOCALE_SMONTHNAME9: "September",
        LOCALE_SMONTHNAME10: "October",
        LOCALE_SMONTHNAME11: "November",
        LOCALE_SMONTHNAME12: "December",
        LOCALE_SMONTHNAME13: "",
        LOCALE_SNATIVECOUNTRYNAME: "Invariant Country",
        LOCALE_SNATIVECTRYNAME: "Invariant Country",
        LOCALE_SNATIVECURRNAME: "International Monetary Fund",
        LOCALE_SNATIVEDIGITS: "0123456789",
        LOCALE_SNATIVEDISPLAYNAME: "Invariant Language (Invariant Region)",
        LOCALE_SNATIVELANGNAME: "Invariant Language",
        LOCALE_SNATIVELANGUAGENAME: "Invariant Language",
        LOCALE_SNEGATIVESIGN: "-",
        LOCALE_SOPENTYPELANGUAGETAG: "dflt",
        LOCALE_SPECIFICDATA: "dddd, dd MMMM yyyy",
        LOCALE_SPERCENT: "%",
        LOCALE_SPERMILLE: "?",
        LOCALE_SPOSITIVESIGN: "+",
        LOCALE_SSHORTDATE: "MM/dd/yyyy",
        LOCALE_SSHORTESTAM: "a",
        LOCALE_SSHORTESTPM: "p",
        LOCALE_SSHORTTIME: "HH:mm",
        LOCALE_SSORTLOCALE: "",
        LOCALE_SSORTNAME: "Math Alphanumerics",
        LOCALE_STHOUSAND: ",",
        LOCALE_STIME: ":",
        LOCALE_STIMEFORMAT: "HH:mm:ss",
        LOCALE_SUPPLEMENTAL: "Invariant Language (Invariant Country)",
        LOCALE_SYEARMONTH: "yyyy MMMM",
        LOCALE_SYSTEM_DEFAULT: "error 1004",
        LOCALE_USE_CP_ACP: "error 1004",
        LOCALE_USER_DEFAULT: "error 1004",
        LOCALE_WINDOWS: "007f",
        LOCALE_S1159: "AM",
        LOCALE_SABBREVLANGNAME: "IVL",
        LOCALE_S2359: "PM",
        DateTimeFormat: {
            "AMDesignator": "AM",
            "Calendar": {
                "MinSupportedDateTime": "0001-01-01T00:00:00",
                "MaxSupportedDateTime": "9999-12-31T23:59:59.9999999",
                "AlgorithmType": 1,
                "CalendarType": 1,
                "Eras": [
                    1
                ],
                "TwoDigitYearMax": 2049,
                "IsReadOnly": false
            },
            "DateSeparator": "/",
            "FirstDayOfWeek": 0,
            "CalendarWeekRule": 0,
            "FullDateTimePattern": "dddd, MMMM d, yyyy h:mm:ss tt",
            "LongDatePattern": "dddd, MMMM d, yyyy",
            "LongTimePattern": "h:mm:ss tt",
            "MonthDayPattern": "MMMM d",
            "PMDesignator": "PM",
            "RFC1123Pattern": "ddd, dd MMM yyyy HH':'mm':'ss 'GMT'",
            "ShortDatePattern": "M/d/yyyy",
            "ShortTimePattern": "h:mm tt",
            "SortableDateTimePattern": "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
            "TimeSeparator": ":",
            "UniversalSortableDateTimePattern": "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
            "YearMonthPattern": "MMMM yyyy",
            "AbbreviatedDayNames": [
                "Sun",
                "Mon",
                "Tue",
                "Wed",
                "Thu",
                "Fri",
                "Sat"
            ],
            "ShortestDayNames": [
                "Su",
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa"
            ],
            "DayNames": [
                "Sunday",
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
            ],
            "AbbreviatedMonthNames": [
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
                ""
            ],
            "MonthNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
                ""
            ],
            "IsReadOnly": false,
            "NativeCalendarName": "Gregorian Calendar",
            "AbbreviatedMonthGenitiveNames": [
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
                ""
            ],
            "MonthGenitiveNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
                ""
            ]
        },
        NumberFormat: {
            "CurrencyDecimalDigits": 2,
            "CurrencyDecimalSeparator": ".",
            "IsReadOnly": false,
            "CurrencyGroupSizes": [
                3
            ],
            "NumberGroupSizes": [
                3
            ],
            "PercentGroupSizes": [
                3
            ],
            "CurrencyGroupSeparator": ",",
            "CurrencySymbol": "$",
            "NaNSymbol": "NaN",
            "CurrencyNegativePattern": 0,
            "NumberNegativePattern": 1,
            "PercentPositivePattern": 1,
            "PercentNegativePattern": 1,
            "NegativeInfinitySymbol": "-∞",
            "NegativeSign": "-",
            "NumberDecimalDigits": 2,
            "NumberDecimalSeparator": ".",
            "NumberGroupSeparator": ",",
            "CurrencyPositivePattern": 0,
            "PositiveInfinitySymbol": "∞",
            "PositiveSign": "+",
            "PercentDecimalDigits": 2,
            "PercentDecimalSeparator": ".",
            "PercentGroupSeparator": ",",
            "PercentSymbol": "%",
            "PerMilleSymbol": "‰",
            "NativeDigits": [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9"
            ],
            "DigitSubstitution": 1
        }
    },
    "en": {
        Locale: "en",
        LCID: "0x409",
        LOCALE_SNAME: "en",
        LOCALE_SPARENT: "",
        LOCALE_SDURATION: "h:mm:ss",
        LOCALE_SKEYBOARDSTOINSTALL: "0409:00000409",
        LOCALE_SSHORTESTDAYNAME1: "Mo",
        LOCALE_SSHORTESTDAYNAME2: "Tu",
        LOCALE_SSHORTESTDAYNAME3: "We",
        LOCALE_SSHORTESTDAYNAME4: "Th",
        LOCALE_SSHORTESTDAYNAME5: "Fr",
        LOCALE_SSHORTESTDAYNAME6: "Sa",
        LOCALE_SSHORTESTDAYNAME7: "Su",
        LOCALE_SISO639LANGNAME2: "eng",
        LOCALE_SISO3166CTRYNAME2: "USA",
        LOCALE_SNAN: "NaN",
        LOCALE_SPOSINFINITY: "?",
        LOCALE_SNEGINFINITY: "-?",
        LOCALE_SSCRIPTS: "Latn;",
        LOCALE_IDATE: "0",
        LOCALE_SDECIMAL: ".",
        LOCALE_SLOCALIZEDCOUNTRYNAME: "United States",
        LOCALE_ALLOW_NEUTRAL_NAMES: "error 1004",
        LOCALE_ALTERNATE_SORTS: "English",
        LOCALE_CUSTOM_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UI_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UNSPECIFIED: "error 1004",
        LOCALE_ICALENDARTYPE: "1",
        LOCALE_ICENTURY: "1",
        LOCALE_IDIALINGCODE: "1",
        LOCALE_ICOUNTRY: "1",
        LOCALE_ICURRDIGITS: "2",
        LOCALE_ICURRENCY: "0",
        LOCALE_IDAYLZERO: "0",
        LOCALE_IDEFAULTANSICODEPAGE: "1252",
        LOCALE_IDEFAULTCODEPAGE: "437",
        LOCALE_IDEFAULTCOUNTRY: "1",
        LOCALE_IDEFAULTEBCDICCODEPAGE: "037",
        LOCALE_IDEFAULTLANGUAGE: "0409",
        LOCALE_IDEFAULTMACCODEPAGE: "10000",
        LOCALE_IDIGITS: "2",
        LOCALE_IDIGITSUBSTITUTION: "1",
        LOCALE_IFIRSTDAYOFWEEK: "6",
        LOCALE_IFIRSTWEEKOFYEAR: "0",
        LOCALE_IGEOID: "244",
        LOCALE_IINTLCURRDIGITS: "2",
        LOCALE_ILANGUAGE: "0409",
        LOCALE_ILDATE: "0",
        LOCALE_ILZERO: "1",
        LOCALE_IMEASURE: "1",
        LOCALE_IMONLZERO: "0",
        LOCALE_INEGATIVEPERCENT: "1",
        LOCALE_INEGCURR: "0",
        LOCALE_INEGNUMBER: "1",
        LOCALE_INEGSEPBYSPACE: "0",
        LOCALE_INEGSIGNPOSN: "0",
        LOCALE_INEGSYMPRECEDES: "1",
        LOCALE_INEUTRAL: "1",
        LOCALE_INVARIANT: "p",
        LOCALE_IOPTIONALCALENDAR: "2",
        LOCALE_IPAPERSIZE: "1",
        LOCALE_IPOSITIVEPERCENT: "1",
        LOCALE_IPOSSEPBYSPACE: "0",
        LOCALE_IPOSSIGNPOSN: "3",
        LOCALE_IPOSSYMPRECEDES: "1",
        LOCALE_IREADINGLAYOUT: "0",
        LOCALE_ITIME: "0",
        LOCALE_ITIMEMARKPOSN: "0",
        LOCALE_ITLZERO: "0",
        LOCALE_NEUTRAL: "error 1004",
        LOCALE_NEUTRALDATA: "3;0",
        LOCALE_REPLACEMENT: "United States",
        LOCALE_SCOUNTRY: "United States",
        LOCALE_SCURRENCY: "$",
        LOCALE_SDATE: "/",
        LOCALE_SDAYNAME1: "Monday",
        LOCALE_SDAYNAME2: "Tuesday",
        LOCALE_SDAYNAME3: "Wednesday",
        LOCALE_SDAYNAME4: "Thursday",
        LOCALE_SDAYNAME5: "Friday",
        LOCALE_SDAYNAME6: "Saturday",
        LOCALE_SDAYNAME7: "Sunday",
        LOCALE_SENGLISHCOUNTRYNAME: "United States",
        LOCALE_SENGLISHDISPLAYNAME: "English",
        LOCALE_SENGLISHLANGUAGENAME: "English",
        LOCALE_SGROUPING: "3;0",
        LOCALE_SINTLSYMBOL: "USD",
        LOCALE_SISO3166CTRYNAME: "US",
        LOCALE_SISO639LANGNAME: "en",
        LOCALE_SLANGDISPLAYNAME: "English",
        LOCALE_SLANGUAGE: "English",
        LOCALE_SLIST: ",",
        LOCALE_SLOCALIZEDDISPLAYNAME: "English",
        LOCALE_SLOCALIZEDLANGUAGENAME: "English",
        LOCALE_SLONGDATE: "dddd, MMMM d, yyyy",
        LOCALE_SMONDECIMALSEP: ".",
        LOCALE_SMONGROUPING: "3;0",
        LOCALE_SMONTHOUSANDSEP: ",",
        LOCALE_SMONTHDAY: "MMMM d",
        LOCALE_SMONTHNAME1: "January",
        LOCALE_SMONTHNAME2: "February",
        LOCALE_SMONTHNAME3: "March",
        LOCALE_SMONTHNAME4: "April",
        LOCALE_SMONTHNAME5: "May",
        LOCALE_SMONTHNAME6: "June",
        LOCALE_SMONTHNAME7: "July",
        LOCALE_SMONTHNAME8: "August",
        LOCALE_SMONTHNAME9: "September",
        LOCALE_SMONTHNAME10: "October",
        LOCALE_SMONTHNAME11: "November",
        LOCALE_SMONTHNAME12: "December",
        LOCALE_SMONTHNAME13: "",
        LOCALE_SNATIVECOUNTRYNAME: "United States",
        LOCALE_SNATIVECTRYNAME: "United States",
        LOCALE_SNATIVECURRNAME: "US Dollar",
        LOCALE_SNATIVEDIGITS: "0123456789",
        LOCALE_SNATIVEDISPLAYNAME: "English",
        LOCALE_SNATIVELANGNAME: "English",
        LOCALE_SNATIVELANGUAGENAME: "English",
        LOCALE_SNEGATIVESIGN: "-",
        LOCALE_SOPENTYPELANGUAGETAG: "ENG ",
        LOCALE_SPECIFICDATA: "dddd, MMMM d, yyyy",
        LOCALE_SPERCENT: "%",
        LOCALE_SPERMILLE: "?",
        LOCALE_SPOSITIVESIGN: "",
        LOCALE_SSHORTDATE: "M/d/yyyy",
        LOCALE_SSHORTESTAM: "a",
        LOCALE_SSHORTESTPM: "p",
        LOCALE_SSHORTTIME: "h:mm tt",
        LOCALE_SSORTLOCALE: "en-US",
        LOCALE_SSORTNAME: "Default",
        LOCALE_STHOUSAND: ",",
        LOCALE_STIME: ":",
        LOCALE_STIMEFORMAT: "h:mm:ss tt",
        LOCALE_SUPPLEMENTAL: "English",
        LOCALE_SYEARMONTH: "MMMM yyyy",
        LOCALE_SYSTEM_DEFAULT: "error 1004",
        LOCALE_USE_CP_ACP: "error 1004",
        LOCALE_USER_DEFAULT: "error 1004",
        LOCALE_WINDOWS: "0409",
        LOCALE_S1159: "AM",
        LOCALE_SABBREVLANGNAME: "ENU",
        LOCALE_S2359: "PM",
        DateTimeFormat: {
            "AMDesignator": "AM",
            "Calendar": {
                "MinSupportedDateTime": "0001-01-01T00:00:00",
                "MaxSupportedDateTime": "9999-12-31T23:59:59.9999999",
                "AlgorithmType": 1,
                "CalendarType": 1,
                "Eras": [
                    1
                ],
                "TwoDigitYearMax": 2049,
                "IsReadOnly": false
            },
            "DateSeparator": "/",
            "FirstDayOfWeek": 0,
            "CalendarWeekRule": 0,
            "FullDateTimePattern": "dddd, MMMM d, yyyy h:mm:ss tt",
            "LongDatePattern": "dddd, MMMM d, yyyy",
            "LongTimePattern": "h:mm:ss tt",
            "MonthDayPattern": "MMMM d",
            "PMDesignator": "PM",
            "RFC1123Pattern": "ddd, dd MMM yyyy HH':'mm':'ss 'GMT'",
            "ShortDatePattern": "M/d/yyyy",
            "ShortTimePattern": "h:mm tt",
            "SortableDateTimePattern": "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
            "TimeSeparator": ":",
            "UniversalSortableDateTimePattern": "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
            "YearMonthPattern": "MMMM yyyy",
            "AbbreviatedDayNames": [
                "Sun",
                "Mon",
                "Tue",
                "Wed",
                "Thu",
                "Fri",
                "Sat"
            ],
            "ShortestDayNames": [
                "Su",
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa"
            ],
            "DayNames": [
                "Sunday",
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
            ],
            "AbbreviatedMonthNames": [
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
                ""
            ],
            "MonthNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
                ""
            ],
            "IsReadOnly": false,
            "NativeCalendarName": "Gregorian Calendar",
            "AbbreviatedMonthGenitiveNames": [
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
                ""
            ],
            "MonthGenitiveNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
                ""
            ]
        },
        NumberFormat: {
            "CurrencyDecimalDigits": 2,
            "CurrencyDecimalSeparator": ".",
            "IsReadOnly": false,
            "CurrencyGroupSizes": [
                3
            ],
            "NumberGroupSizes": [
                3
            ],
            "PercentGroupSizes": [
                3
            ],
            "CurrencyGroupSeparator": ",",
            "CurrencySymbol": "$",
            "NaNSymbol": "NaN",
            "CurrencyNegativePattern": 0,
            "NumberNegativePattern": 1,
            "PercentPositivePattern": 1,
            "PercentNegativePattern": 1,
            "NegativeInfinitySymbol": "-∞",
            "NegativeSign": "-",
            "NumberDecimalDigits": 2,
            "NumberDecimalSeparator": ".",
            "NumberGroupSeparator": ",",
            "CurrencyPositivePattern": 0,
            "PositiveInfinitySymbol": "∞",
            "PositiveSign": "+",
            "PercentDecimalDigits": 2,
            "PercentDecimalSeparator": ".",
            "PercentGroupSeparator": ",",
            "PercentSymbol": "%",
            "PerMilleSymbol": "‰",
            "NativeDigits": [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9"
            ],
            "DigitSubstitution": 1
        }
    },
    "en-US": {
        Locale: "en-US",
        LCID: "0x409",
        LOCALE_SNAME: "en-US",
        LOCALE_SPARENT: "en",
        LOCALE_SDURATION: "h:mm:ss",
        LOCALE_SKEYBOARDSTOINSTALL: "0409:00000409",
        LOCALE_SSHORTESTDAYNAME1: "Mo",
        LOCALE_SSHORTESTDAYNAME2: "Tu",
        LOCALE_SSHORTESTDAYNAME3: "We",
        LOCALE_SSHORTESTDAYNAME4: "Th",
        LOCALE_SSHORTESTDAYNAME5: "Fr",
        LOCALE_SSHORTESTDAYNAME6: "Sa",
        LOCALE_SSHORTESTDAYNAME7: "Su",
        LOCALE_SISO639LANGNAME2: "eng",
        LOCALE_SISO3166CTRYNAME2: "USA",
        LOCALE_SNAN: "NaN",
        LOCALE_SPOSINFINITY: "?",
        LOCALE_SNEGINFINITY: "-?",
        LOCALE_SSCRIPTS: "Latn;",
        LOCALE_IDATE: "0",
        LOCALE_SDECIMAL: ".",
        LOCALE_SLOCALIZEDCOUNTRYNAME: "United States",
        LOCALE_ALLOW_NEUTRAL_NAMES: "error 1004",
        LOCALE_ALTERNATE_SORTS: "English",
        LOCALE_CUSTOM_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UI_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UNSPECIFIED: "error 1004",
        LOCALE_ICALENDARTYPE: "1",
        LOCALE_ICENTURY: "1",
        LOCALE_IDIALINGCODE: "1",
        LOCALE_ICOUNTRY: "1",
        LOCALE_ICURRDIGITS: "2",
        LOCALE_ICURRENCY: "0",
        LOCALE_IDAYLZERO: "0",
        LOCALE_IDEFAULTANSICODEPAGE: "1252",
        LOCALE_IDEFAULTCODEPAGE: "437",
        LOCALE_IDEFAULTCOUNTRY: "1",
        LOCALE_IDEFAULTEBCDICCODEPAGE: "037",
        LOCALE_IDEFAULTLANGUAGE: "0409",
        LOCALE_IDEFAULTMACCODEPAGE: "10000",
        LOCALE_IDIGITS: "2",
        LOCALE_IDIGITSUBSTITUTION: "1",
        LOCALE_IFIRSTDAYOFWEEK: "6",
        LOCALE_IFIRSTWEEKOFYEAR: "0",
        LOCALE_IGEOID: "244",
        LOCALE_IINTLCURRDIGITS: "2",
        LOCALE_ILANGUAGE: "0409",
        LOCALE_ILDATE: "0",
        LOCALE_ILZERO: "1",
        LOCALE_IMEASURE: "1",
        LOCALE_IMONLZERO: "0",
        LOCALE_INEGATIVEPERCENT: "1",
        LOCALE_INEGCURR: "0",
        LOCALE_INEGNUMBER: "1",
        LOCALE_INEGSEPBYSPACE: "0",
        LOCALE_INEGSIGNPOSN: "0",
        LOCALE_INEGSYMPRECEDES: "1",
        LOCALE_INEUTRAL: "0",
        LOCALE_INVARIANT: "p",
        LOCALE_IOPTIONALCALENDAR: "2",
        LOCALE_IPAPERSIZE: "1",
        LOCALE_IPOSITIVEPERCENT: "1",
        LOCALE_IPOSSEPBYSPACE: "0",
        LOCALE_IPOSSIGNPOSN: "3",
        LOCALE_IPOSSYMPRECEDES: "1",
        LOCALE_IREADINGLAYOUT: "0",
        LOCALE_ITIME: "0",
        LOCALE_ITIMEMARKPOSN: "0",
        LOCALE_ITLZERO: "0",
        LOCALE_NEUTRAL: "error 1004",
        LOCALE_NEUTRALDATA: "3;0",
        LOCALE_REPLACEMENT: "United States",
        LOCALE_SCOUNTRY: "United States",
        LOCALE_SCURRENCY: "$",
        LOCALE_SDATE: "/",
        LOCALE_SDAYNAME1: "Monday",
        LOCALE_SDAYNAME2: "Tuesday",
        LOCALE_SDAYNAME3: "Wednesday",
        LOCALE_SDAYNAME4: "Thursday",
        LOCALE_SDAYNAME5: "Friday",
        LOCALE_SDAYNAME6: "Saturday",
        LOCALE_SDAYNAME7: "Sunday",
        LOCALE_SENGLISHCOUNTRYNAME: "United States",
        LOCALE_SENGLISHDISPLAYNAME: "English (United States)",
        LOCALE_SENGLISHLANGUAGENAME: "English",
        LOCALE_SGROUPING: "3;0",
        LOCALE_SINTLSYMBOL: "USD",
        LOCALE_SISO3166CTRYNAME: "US",
        LOCALE_SISO639LANGNAME: "en",
        LOCALE_SLANGDISPLAYNAME: "English",
        LOCALE_SLANGUAGE: "English (United States)",
        LOCALE_SLIST: ",",
        LOCALE_SLOCALIZEDDISPLAYNAME: "English (United States)",
        LOCALE_SLOCALIZEDLANGUAGENAME: "English",
        LOCALE_SLONGDATE: "dddd, MMMM d, yyyy",
        LOCALE_SMONDECIMALSEP: ".",
        LOCALE_SMONGROUPING: "3;0",
        LOCALE_SMONTHOUSANDSEP: ",",
        LOCALE_SMONTHDAY: "MMMM d",
        LOCALE_SMONTHNAME1: "January",
        LOCALE_SMONTHNAME2: "February",
        LOCALE_SMONTHNAME3: "March",
        LOCALE_SMONTHNAME4: "April",
        LOCALE_SMONTHNAME5: "May",
        LOCALE_SMONTHNAME6: "June",
        LOCALE_SMONTHNAME7: "July",
        LOCALE_SMONTHNAME8: "August",
        LOCALE_SMONTHNAME9: "September",
        LOCALE_SMONTHNAME10: "October",
        LOCALE_SMONTHNAME11: "November",
        LOCALE_SMONTHNAME12: "December",
        LOCALE_SMONTHNAME13: "",
        LOCALE_SNATIVECOUNTRYNAME: "United States",
        LOCALE_SNATIVECTRYNAME: "United States",
        LOCALE_SNATIVECURRNAME: "US Dollar",
        LOCALE_SNATIVEDIGITS: "0123456789",
        LOCALE_SNATIVEDISPLAYNAME: "English (United States)",
        LOCALE_SNATIVELANGNAME: "English",
        LOCALE_SNATIVELANGUAGENAME: "English",
        LOCALE_SNEGATIVESIGN: "-",
        LOCALE_SOPENTYPELANGUAGETAG: "ENG ",
        LOCALE_SPECIFICDATA: "dddd, MMMM d, yyyy",
        LOCALE_SPERCENT: "%",
        LOCALE_SPERMILLE: "?",
        LOCALE_SPOSITIVESIGN: "",
        LOCALE_SSHORTDATE: "M/d/yyyy",
        LOCALE_SSHORTESTAM: "a",
        LOCALE_SSHORTESTPM: "p",
        LOCALE_SSHORTTIME: "h:mm tt",
        LOCALE_SSORTLOCALE: "en-US",
        LOCALE_SSORTNAME: "Default",
        LOCALE_STHOUSAND: ",",
        LOCALE_STIME: ":",
        LOCALE_STIMEFORMAT: "h:mm:ss tt",
        LOCALE_SUPPLEMENTAL: "English (United States)",
        LOCALE_SYEARMONTH: "MMMM yyyy",
        LOCALE_SYSTEM_DEFAULT: "error 1004",
        LOCALE_USE_CP_ACP: "error 1004",
        LOCALE_USER_DEFAULT: "error 1004",
        LOCALE_WINDOWS: "0409",
        LOCALE_S1159: "AM",
        LOCALE_SABBREVLANGNAME: "ENU",
        LOCALE_S2359: "PM",
        DateTimeFormat: {
            "AMDesignator": "AM",
            "Calendar": {
                "MinSupportedDateTime": "0001-01-01T00:00:00",
                "MaxSupportedDateTime": "9999-12-31T23:59:59.9999999",
                "AlgorithmType": 1,
                "CalendarType": 1,
                "Eras": [
                    1
                ],
                "TwoDigitYearMax": 2049,
                "IsReadOnly": false
            },
            "DateSeparator": "/",
            "FirstDayOfWeek": 0,
            "CalendarWeekRule": 0,
            "FullDateTimePattern": "dddd, MMMM d, yyyy h:mm:ss tt",
            "LongDatePattern": "dddd, MMMM d, yyyy",
            "LongTimePattern": "h:mm:ss tt",
            "MonthDayPattern": "MMMM d",
            "PMDesignator": "PM",
            "RFC1123Pattern": "ddd, dd MMM yyyy HH':'mm':'ss 'GMT'",
            "ShortDatePattern": "M/d/yyyy",
            "ShortTimePattern": "h:mm tt",
            "SortableDateTimePattern": "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
            "TimeSeparator": ":",
            "UniversalSortableDateTimePattern": "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
            "YearMonthPattern": "MMMM yyyy",
            "AbbreviatedDayNames": [
                "Sun",
                "Mon",
                "Tue",
                "Wed",
                "Thu",
                "Fri",
                "Sat"
            ],
            "ShortestDayNames": [
                "Su",
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa"
            ],
            "DayNames": [
                "Sunday",
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
            ],
            "AbbreviatedMonthNames": [
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
                ""
            ],
            "MonthNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
                ""
            ],
            "IsReadOnly": false,
            "NativeCalendarName": "Gregorian Calendar",
            "AbbreviatedMonthGenitiveNames": [
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
                ""
            ],
            "MonthGenitiveNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
                ""
            ]
        },
        NumberFormat: {
            "CurrencyDecimalDigits": 2,
            "CurrencyDecimalSeparator": ".",
            "IsReadOnly": false,
            "CurrencyGroupSizes": [
                3
            ],
            "NumberGroupSizes": [
                3
            ],
            "PercentGroupSizes": [
                3
            ],
            "CurrencyGroupSeparator": ",",
            "CurrencySymbol": "$",
            "NaNSymbol": "NaN",
            "CurrencyNegativePattern": 0,
            "NumberNegativePattern": 1,
            "PercentPositivePattern": 1,
            "PercentNegativePattern": 1,
            "NegativeInfinitySymbol": "-∞",
            "NegativeSign": "-",
            "NumberDecimalDigits": 2,
            "NumberDecimalSeparator": ".",
            "NumberGroupSeparator": ",",
            "CurrencyPositivePattern": 0,
            "PositiveInfinitySymbol": "∞",
            "PositiveSign": "+",
            "PercentDecimalDigits": 2,
            "PercentDecimalSeparator": ".",
            "PercentGroupSeparator": ",",
            "PercentSymbol": "%",
            "PerMilleSymbol": "‰",
            "NativeDigits": [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9"
            ],
            "DigitSubstitution": 1
        }
    },
    'tr': {
        Locale: "tr",
        LCID: "0x41f",
        LOCALE_SNAME: "tr",
        LOCALE_SPARENT: "",
        LOCALE_SDURATION: "h:mm:ss",
        LOCALE_SKEYBOARDSTOINSTALL: "041f:0000041f",
        LOCALE_SSHORTESTDAYNAME1: "Pt",
        LOCALE_SSHORTESTDAYNAME2: "Sa",
        LOCALE_SSHORTESTDAYNAME3: "Ça",
        LOCALE_SSHORTESTDAYNAME4: "Pe",
        LOCALE_SSHORTESTDAYNAME5: "Cu",
        LOCALE_SSHORTESTDAYNAME6: "Ct",
        LOCALE_SSHORTESTDAYNAME7: "Pa",
        LOCALE_SISO639LANGNAME2: "tur",
        LOCALE_SISO3166CTRYNAME2: "TUR",
        LOCALE_SNAN: "NaN",
        LOCALE_SPOSINFINITY: "?",
        LOCALE_SNEGINFINITY: "-?",
        LOCALE_SSCRIPTS: "Latn;",
        LOCALE_IDATE: "1",
        LOCALE_SDECIMAL: ",",
        LOCALE_SLOCALIZEDCOUNTRYNAME: "Turkey",
        LOCALE_ALLOW_NEUTRAL_NAMES: "error 1004",
        LOCALE_ALTERNATE_SORTS: "Türkçe",
        LOCALE_CUSTOM_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UI_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UNSPECIFIED: "error 1004",
        LOCALE_ICALENDARTYPE: "1",
        LOCALE_ICENTURY: "1",
        LOCALE_IDIALINGCODE: "90",
        LOCALE_ICOUNTRY: "90",
        LOCALE_ICURRDIGITS: "2",
        LOCALE_ICURRENCY: "0",
        LOCALE_IDAYLZERO: "0",
        LOCALE_IDEFAULTANSICODEPAGE: "1254",
        LOCALE_IDEFAULTCODEPAGE: "857",
        LOCALE_IDEFAULTCOUNTRY: "90",
        LOCALE_IDEFAULTEBCDICCODEPAGE: "20905",
        LOCALE_IDEFAULTLANGUAGE: "041f",
        LOCALE_IDEFAULTMACCODEPAGE: "10081",
        LOCALE_IDIGITS: "2",
        LOCALE_IDIGITSUBSTITUTION: "1",
        LOCALE_IFIRSTDAYOFWEEK: "0",
        LOCALE_IFIRSTWEEKOFYEAR: "0",
        LOCALE_IGEOID: "235",
        LOCALE_IINTLCURRDIGITS: "2",
        LOCALE_ILANGUAGE: "041f",
        LOCALE_ILDATE: "1",
        LOCALE_ILZERO: "1",
        LOCALE_IMEASURE: "0",
        LOCALE_IMONLZERO: "1",
        LOCALE_INEGATIVEPERCENT: "2",
        LOCALE_INEGCURR: "1",
        LOCALE_INEGNUMBER: "1",
        LOCALE_INEGSEPBYSPACE: "0",
        LOCALE_INEGSIGNPOSN: "3",
        LOCALE_INEGSYMPRECEDES: "1",
        LOCALE_INEUTRAL: "1",
        LOCALE_INVARIANT: "ös",
        LOCALE_IOPTIONALCALENDAR: "6",
        LOCALE_IPAPERSIZE: "9",
        LOCALE_IPOSITIVEPERCENT: "2",
        LOCALE_IPOSSEPBYSPACE: "0",
        LOCALE_IPOSSIGNPOSN: "3",
        LOCALE_IPOSSYMPRECEDES: "1",
        LOCALE_IREADINGLAYOUT: "0",
        LOCALE_ITIME: "1",
        LOCALE_ITIMEMARKPOSN: "0",
        LOCALE_ITLZERO: "1",
        LOCALE_NEUTRAL: "error 1004",
        LOCALE_NEUTRALDATA: "3;0",
        LOCALE_REPLACEMENT: "Türkiye",
        LOCALE_SCOUNTRY: "Turkey",
        LOCALE_SCURRENCY: "?",
        LOCALE_SDATE: ".",
        LOCALE_SDAYNAME1: "Pazartesi",
        LOCALE_SDAYNAME2: "Sal?",
        LOCALE_SDAYNAME3: "Çar?amba",
        LOCALE_SDAYNAME4: "Per?embe",
        LOCALE_SDAYNAME5: "Cuma",
        LOCALE_SDAYNAME6: "Cumartesi",
        LOCALE_SDAYNAME7: "Pazar",
        LOCALE_SENGLISHCOUNTRYNAME: "Turkey",
        LOCALE_SENGLISHDISPLAYNAME: "Turkish",
        LOCALE_SENGLISHLANGUAGENAME: "Turkish",
        LOCALE_SGROUPING: "3;0",
        LOCALE_SINTLSYMBOL: "TRY",
        LOCALE_SISO3166CTRYNAME: "TR",
        LOCALE_SISO639LANGNAME: "tr",
        LOCALE_SLANGDISPLAYNAME: "Turkish",
        LOCALE_SLANGUAGE: "Turkish",
        LOCALE_SLIST: ";",
        LOCALE_SLOCALIZEDDISPLAYNAME: "Turkish",
        LOCALE_SLOCALIZEDLANGUAGENAME: "Turkish",
        LOCALE_SLONGDATE: "d MMMM yyyy dddd",
        LOCALE_SMONDECIMALSEP: ",",
        LOCALE_SMONGROUPING: "3;0",
        LOCALE_SMONTHOUSANDSEP: ".",
        LOCALE_SMONTHDAY: "d MMMM",
        LOCALE_SMONTHNAME1: "Ocak",
        LOCALE_SMONTHNAME2: "?ubat",
        LOCALE_SMONTHNAME3: "Mart",
        LOCALE_SMONTHNAME4: "Nisan",
        LOCALE_SMONTHNAME5: "May?s",
        LOCALE_SMONTHNAME6: "Haziran",
        LOCALE_SMONTHNAME7: "Temmuz",
        LOCALE_SMONTHNAME8: "A?ustos",
        LOCALE_SMONTHNAME9: "Eylül",
        LOCALE_SMONTHNAME10: "Ekim",
        LOCALE_SMONTHNAME11: "Kas?m",
        LOCALE_SMONTHNAME12: "Aral?k",
        LOCALE_SMONTHNAME13: "",
        LOCALE_SNATIVECOUNTRYNAME: "Türkiye",
        LOCALE_SNATIVECTRYNAME: "Türkiye",
        LOCALE_SNATIVECURRNAME: "Türk Liras?",
        LOCALE_SNATIVEDIGITS: "0123456789",
        LOCALE_SNATIVEDISPLAYNAME: "Türkçe",
        LOCALE_SNATIVELANGNAME: "Türkçe",
        LOCALE_SNATIVELANGUAGENAME: "Türkçe",
        LOCALE_SNEGATIVESIGN: "-",
        LOCALE_SOPENTYPELANGUAGETAG: "TRK ",
        LOCALE_SPECIFICDATA: "d MMMM yyyy dddd",
        LOCALE_SPERCENT: "%",
        LOCALE_SPERMILLE: "?",
        LOCALE_SPOSITIVESIGN: "",
        LOCALE_SSHORTDATE: "d.MM.yyyy",
        LOCALE_SSHORTESTAM: "öö",
        LOCALE_SSHORTESTPM: "ös",
        LOCALE_SSHORTTIME: "HH:mm",
        LOCALE_SSORTLOCALE: "tr-TR",
        LOCALE_SSORTNAME: "Default",
        LOCALE_STHOUSAND: ".",
        LOCALE_STIME: ":",
        LOCALE_STIMEFORMAT: "HH:mm:ss",
        LOCALE_SUPPLEMENTAL: "Turkish",
        LOCALE_SYEARMONTH: "MMMM yyyy",
        LOCALE_SYSTEM_DEFAULT: "error 1004",
        LOCALE_USE_CP_ACP: "error 1004",
        LOCALE_USER_DEFAULT: "error 1004",
        LOCALE_WINDOWS: "041f",
        LOCALE_S1159: "ÖÖ",
        LOCALE_SABBREVLANGNAME: "TRK",
        LOCALE_S2359: "ÖS",
        DateTimeFormat: {
            "AMDesignator": "ÖÖ",
            "Calendar": {
                "MinSupportedDateTime": "0001-01-01T00:00:00",
                "MaxSupportedDateTime": "9999-12-31T23:59:59.9999999",
                "AlgorithmType": 1,
                "CalendarType": 1,
                "Eras": [
                    1
                ],
                "TwoDigitYearMax": 2049,
                "IsReadOnly": false
            },
            DateSeparator: ".",
            FirstDayOfWeek: 1,
            CalendarWeekRule: 0,
            FullDateTimePattern: "d MMMM yyyy dddd HH:mm:ss",
            LongDatePattern: "d MMMM yyyy dddd",
            LongTimePattern: "HH:mm:ss",
            MonthDayPattern: "d MMMM",
            PMDesignator: "ÖS",
            RFC1123Pattern: "ddd, dd MMM yyyy HH':'mm':'ss 'GMT'",
            ShortDatePattern: "d.MM.yyyy",
            ShortTimePattern: "HH:mm",
            SortableDateTimePattern: "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
            TimeSeparator: ":",
            UniversalSortableDateTimePattern: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
            YearMonthPattern: "MMMM yyyy",
            AbbreviatedDayNames: [
                "Paz",
                "Pzt",
                "Sal",
                "Çar",
                "Per",
                "Cum",
                "Cmt"
            ],
            ShortestDayNames: [
                "Pa",
                "Pt",
                "Sa",
                "Ça",
                "Pe",
                "Cu",
                "Ct"
            ],
            DayNames: [
                "Pazar",
                "Pazartesi",
                "Salı",
                "Çarşamba",
                "Perşembe",
                "Cuma",
                "Cumartesi"
            ],
            AbbreviatedMonthNames: [
                "Oca",
                "Şub",
                "Mar",
                "Nis",
                "May",
                "Haz",
                "Tem",
                "Ağu",
                "Eyl",
                "Eki",
                "Kas",
                "Ara",
                ""
            ],
            MonthNames: [
                "Ocak",
                "Şubat",
                "Mart",
                "Nisan",
                "Mayıs",
                "Haziran",
                "Temmuz",
                "Ağustos",
                "Eylül",
                "Ekim",
                "Kasım",
                "Aralık",
                ""
            ],
            IsReadOnly: false,
            NativeCalendarName: "Miladi Takvim",
            AbbreviatedMonthGenitiveNames: [
                "Oca",
                "Şub",
                "Mar",
                "Nis",
                "May",
                "Haz",
                "Tem",
                "Ağu",
                "Eyl",
                "Eki",
                "Kas",
                "Ara",
                ""
            ],
            MonthGenitiveNames: [
                "Ocak",
                "Şubat",
                "Mart",
                "Nisan",
                "Mayıs",
                "Haziran",
                "Temmuz",
                "Ağustos",
                "Eylül",
                "Ekim",
                "Kasım",
                "Aralık",
                ""
            ]
        },
        NumberFormat: {
            "CurrencyDecimalDigits": 2,
            "CurrencyDecimalSeparator": ",",
            "IsReadOnly": false,
            "CurrencyGroupSizes": [
                3
            ],
            "NumberGroupSizes": [
                3
            ],
            "PercentGroupSizes": [
                3
            ],
            "CurrencyGroupSeparator": ".",
            "CurrencySymbol": "₺",
            "NaNSymbol": "NaN",
            "CurrencyNegativePattern": 1,
            "NumberNegativePattern": 1,
            "PercentPositivePattern": 2,
            "PercentNegativePattern": 2,
            "NegativeInfinitySymbol": "-∞",
            "NegativeSign": "-",
            "NumberDecimalDigits": 2,
            "NumberDecimalSeparator": ",",
            "NumberGroupSeparator": ".",
            "CurrencyPositivePattern": 0,
            "PositiveInfinitySymbol": "∞",
            "PositiveSign": "+",
            "PercentDecimalDigits": 2,
            "PercentDecimalSeparator": ",",
            "PercentGroupSeparator": ".",
            "PercentSymbol": "%",
            "PerMilleSymbol": "‰",
            "NativeDigits": [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9"
            ],
            "DigitSubstitution": 1
        }
    },
    "tr-TR": {
        Locale: "tr-TR",
        LCID: "0x41f",
        LOCALE_SNAME: "tr-TR",
        LOCALE_SPARENT: "tr",
        LOCALE_SDURATION: "h:mm:ss",
        LOCALE_SKEYBOARDSTOINSTALL: "041f:0000041f",
        LOCALE_SSHORTESTDAYNAME1: "Pt",
        LOCALE_SSHORTESTDAYNAME2: "Sa",
        LOCALE_SSHORTESTDAYNAME3: "Ça",
        LOCALE_SSHORTESTDAYNAME4: "Pe",
        LOCALE_SSHORTESTDAYNAME5: "Cu",
        LOCALE_SSHORTESTDAYNAME6: "Ct",
        LOCALE_SSHORTESTDAYNAME7: "Pa",
        LOCALE_SISO639LANGNAME2: "tur",
        LOCALE_SISO3166CTRYNAME2: "TUR",
        LOCALE_SNAN: "NaN",
        LOCALE_SPOSINFINITY: "?",
        LOCALE_SNEGINFINITY: "-?",
        LOCALE_SSCRIPTS: "Latn;",
        LOCALE_IDATE: "1",
        LOCALE_SDECIMAL: ",",
        LOCALE_SLOCALIZEDCOUNTRYNAME: "Turkey",
        LOCALE_ALLOW_NEUTRAL_NAMES: "error 1004",
        LOCALE_ALTERNATE_SORTS: "Türkçe",
        LOCALE_CUSTOM_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UI_DEFAULT: "error 1004",
        LOCALE_CUSTOM_UNSPECIFIED: "error 1004",
        LOCALE_ICALENDARTYPE: "1",
        LOCALE_ICENTURY: "1",
        LOCALE_IDIALINGCODE: "90",
        LOCALE_ICOUNTRY: "90",
        LOCALE_ICURRDIGITS: "2",
        LOCALE_ICURRENCY: "0",
        LOCALE_IDAYLZERO: "0",
        LOCALE_IDEFAULTANSICODEPAGE: "1254",
        LOCALE_IDEFAULTCODEPAGE: "857",
        LOCALE_IDEFAULTCOUNTRY: "90",
        LOCALE_IDEFAULTEBCDICCODEPAGE: "20905",
        LOCALE_IDEFAULTLANGUAGE: "041f",
        LOCALE_IDEFAULTMACCODEPAGE: "10081",
        LOCALE_IDIGITS: "2",
        LOCALE_IDIGITSUBSTITUTION: "1",
        LOCALE_IFIRSTDAYOFWEEK: "0",
        LOCALE_IFIRSTWEEKOFYEAR: "0",
        LOCALE_IGEOID: "235",
        LOCALE_IINTLCURRDIGITS: "2",
        LOCALE_ILANGUAGE: "041f",
        LOCALE_ILDATE: "1",
        LOCALE_ILZERO: "1",
        LOCALE_IMEASURE: "0",
        LOCALE_IMONLZERO: "1",
        LOCALE_INEGATIVEPERCENT: "2",
        LOCALE_INEGCURR: "1",
        LOCALE_INEGNUMBER: "1",
        LOCALE_INEGSEPBYSPACE: "0",
        LOCALE_INEGSIGNPOSN: "3",
        LOCALE_INEGSYMPRECEDES: "1",
        LOCALE_INEUTRAL: "0",
        LOCALE_INVARIANT: "ös",
        LOCALE_IOPTIONALCALENDAR: "6",
        LOCALE_IPAPERSIZE: "9",
        LOCALE_IPOSITIVEPERCENT: "2",
        LOCALE_IPOSSEPBYSPACE: "0",
        LOCALE_IPOSSIGNPOSN: "3",
        LOCALE_IPOSSYMPRECEDES: "1",
        LOCALE_IREADINGLAYOUT: "0",
        LOCALE_ITIME: "1",
        LOCALE_ITIMEMARKPOSN: "0",
        LOCALE_ITLZERO: "1",
        LOCALE_NEUTRAL: "error 1004",
        LOCALE_NEUTRALDATA: "3;0",
        LOCALE_REPLACEMENT: "Türkiye",
        LOCALE_SCOUNTRY: "Turkey",
        LOCALE_SCURRENCY: "?",
        LOCALE_SDATE: ".",
        LOCALE_SDAYNAME1: "Pazartesi",
        LOCALE_SDAYNAME2: "Sal?",
        LOCALE_SDAYNAME3: "Çar?amba",
        LOCALE_SDAYNAME4: "Per?embe",
        LOCALE_SDAYNAME5: "Cuma",
        LOCALE_SDAYNAME6: "Cumartesi",
        LOCALE_SDAYNAME7: "Pazar",
        LOCALE_SENGLISHCOUNTRYNAME: "Turkey",
        LOCALE_SENGLISHDISPLAYNAME: "Turkish (Turkey)",
        LOCALE_SENGLISHLANGUAGENAME: "Turkish",
        LOCALE_SGROUPING: "3;0",
        LOCALE_SINTLSYMBOL: "TRY",
        LOCALE_SISO3166CTRYNAME: "TR",
        LOCALE_SISO639LANGNAME: "tr",
        LOCALE_SLANGDISPLAYNAME: "Turkish",
        LOCALE_SLANGUAGE: "Turkish (Turkey)",
        LOCALE_SLIST: ";",
        LOCALE_SLOCALIZEDDISPLAYNAME: "Turkish (Turkey)",
        LOCALE_SLOCALIZEDLANGUAGENAME: "Turkish",
        LOCALE_SLONGDATE: "d MMMM yyyy dddd",
        LOCALE_SMONDECIMALSEP: ",",
        LOCALE_SMONGROUPING: "3;0",
        LOCALE_SMONTHOUSANDSEP: ".",
        LOCALE_SMONTHDAY: "d MMMM",
        LOCALE_SMONTHNAME1: "Ocak",
        LOCALE_SMONTHNAME2: "?ubat",
        LOCALE_SMONTHNAME3: "Mart",
        LOCALE_SMONTHNAME4: "Nisan",
        LOCALE_SMONTHNAME5: "May?s",
        LOCALE_SMONTHNAME6: "Haziran",
        LOCALE_SMONTHNAME7: "Temmuz",
        LOCALE_SMONTHNAME8: "A?ustos",
        LOCALE_SMONTHNAME9: "Eylül",
        LOCALE_SMONTHNAME10: "Ekim",
        LOCALE_SMONTHNAME11: "Kas?m",
        LOCALE_SMONTHNAME12: "Aral?k",
        LOCALE_SMONTHNAME13: "",
        LOCALE_SNATIVECOUNTRYNAME: "Türkiye",
        LOCALE_SNATIVECTRYNAME: "Türkiye",
        LOCALE_SNATIVECURRNAME: "Türk Liras?",
        LOCALE_SNATIVEDIGITS: "0123456789",
        LOCALE_SNATIVEDISPLAYNAME: "Türkçe (Türkiye)",
        LOCALE_SNATIVELANGNAME: "Türkçe",
        LOCALE_SNATIVELANGUAGENAME: "Türkçe",
        LOCALE_SNEGATIVESIGN: "-",
        LOCALE_SOPENTYPELANGUAGETAG: "TRK ",
        LOCALE_SPECIFICDATA: "d MMMM yyyy dddd",
        LOCALE_SPERCENT: "%",
        LOCALE_SPERMILLE: "?",
        LOCALE_SPOSITIVESIGN: "",
        LOCALE_SSHORTDATE: "d.MM.yyyy",
        LOCALE_SSHORTESTAM: "öö",
        LOCALE_SSHORTESTPM: "ös",
        LOCALE_SSHORTTIME: "HH:mm",
        LOCALE_SSORTLOCALE: "tr-TR",
        LOCALE_SSORTNAME: "Default",
        LOCALE_STHOUSAND: ".",
        LOCALE_STIME: ":",
        LOCALE_STIMEFORMAT: "HH:mm:ss",
        LOCALE_SUPPLEMENTAL: "Turkish (Turkey)",
        LOCALE_SYEARMONTH: "MMMM yyyy",
        LOCALE_SYSTEM_DEFAULT: "error 1004",
        LOCALE_USE_CP_ACP: "error 1004",
        LOCALE_USER_DEFAULT: "error 1004",
        LOCALE_WINDOWS: "041f",
        LOCALE_S1159: "ÖÖ",
        LOCALE_SABBREVLANGNAME: "TRK",
        LOCALE_S2359: "ÖS",
        DateTimeFormat: {
            "AMDesignator": "ÖÖ",
            "Calendar": {
                "MinSupportedDateTime": "0001-01-01T00:00:00",
                "MaxSupportedDateTime": "9999-12-31T23:59:59.9999999",
                "AlgorithmType": 1,
                "CalendarType": 1,
                "Eras": [
                    1
                ],
                "TwoDigitYearMax": 2049,
                "IsReadOnly": false
            },
            DateSeparator: ".",
            FirstDayOfWeek: 1,
            CalendarWeekRule: 0,
            FullDateTimePattern: "d MMMM yyyy dddd HH:mm:ss",
            LongDatePattern: "d MMMM yyyy dddd",
            LongTimePattern: "HH:mm:ss",
            MonthDayPattern: "d MMMM",
            PMDesignator: "ÖS",
            RFC1123Pattern: "ddd, dd MMM yyyy HH':'mm':'ss 'GMT'",
            ShortDatePattern: "d.MM.yyyy",
            ShortTimePattern: "HH:mm",
            SortableDateTimePattern: "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
            TimeSeparator: ":",
            UniversalSortableDateTimePattern: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
            YearMonthPattern: "MMMM yyyy",
            AbbreviatedDayNames: [
                "Paz",
                "Pzt",
                "Sal",
                "Çar",
                "Per",
                "Cum",
                "Cmt"
            ],
            ShortestDayNames: [
                "Pa",
                "Pt",
                "Sa",
                "Ça",
                "Pe",
                "Cu",
                "Ct"
            ],
            DayNames: [
                "Pazar",
                "Pazartesi",
                "Salı",
                "Çarşamba",
                "Perşembe",
                "Cuma",
                "Cumartesi"
            ],
            AbbreviatedMonthNames: [
                "Oca",
                "Şub",
                "Mar",
                "Nis",
                "May",
                "Haz",
                "Tem",
                "Ağu",
                "Eyl",
                "Eki",
                "Kas",
                "Ara",
                ""
            ],
            MonthNames: [
                "Ocak",
                "Şubat",
                "Mart",
                "Nisan",
                "Mayıs",
                "Haziran",
                "Temmuz",
                "Ağustos",
                "Eylül",
                "Ekim",
                "Kasım",
                "Aralık",
                ""
            ],
            IsReadOnly: false,
            NativeCalendarName: "Miladi Takvim",
            AbbreviatedMonthGenitiveNames: [
                "Oca",
                "Şub",
                "Mar",
                "Nis",
                "May",
                "Haz",
                "Tem",
                "Ağu",
                "Eyl",
                "Eki",
                "Kas",
                "Ara",
                ""
            ],
            MonthGenitiveNames: [
                "Ocak",
                "Şubat",
                "Mart",
                "Nisan",
                "Mayıs",
                "Haziran",
                "Temmuz",
                "Ağustos",
                "Eylül",
                "Ekim",
                "Kasım",
                "Aralık",
                ""
            ]
        },
        NumberFormat: {
            CurrencyDecimalDigits: 2,
            CurrencyDecimalSeparator: ",",
            IsReadOnly: false,
            CurrencyGroupSizes: [
                3
            ],
            NumberGroupSizes: [
                3
            ],
            PercentGroupSizes: [
                3
            ],
            CurrencyGroupSeparator: ".",
            CurrencySymbol: "₺",
            NaNSymbol: "NaN",
            CurrencyNegativePattern: 1,
            NumberNegativePattern: 1,
            PercentPositivePattern: 2,
            PercentNegativePattern: 2,
            NegativeInfinitySymbol: "-∞",
            NegativeSign: "-",
            NumberDecimalDigits: 2,
            NumberDecimalSeparator: ",",
            NumberGroupSeparator: ".",
            CurrencyPositivePattern: 0,
            PositiveInfinitySymbol: "∞",
            PositiveSign: "+",
            PercentDecimalDigits: 2,
            PercentDecimalSeparator: ",",
            PercentGroupSeparator: ".",
            PercentSymbol: "%",
            PerMilleSymbol: "‰",
            NativeDigits: [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9"
            ],
            DigitSubstitution: 1
        },
    }
}